### ISSUE TITLE
Support for NamedCache

### ISSUE THREAD

**Issue by rval** [KarelCemus/play-redis#106]
Hello there, I’m looking to use `play-redis` in an upcoming project, but have some modules that depend on Play’s `NamedCache` [feature](https://www.playframework.com/documentation/2.6.x/ScalaCache#Accessing-different-caches). 

Is support for `NamedCache` on your road map? Would you be open to a pull request implementing this support?

Thanks for the excellent module!

**Comment by KarelCemus** [comment]
Hi, thanks for your contribution.

Well, there is no support so far and was not on road map either as I didn't know somebody actually uses that. However, as the request is here, I'll look at it ASAP and let you know whether I'll do it myself or give you some guidance for PR.

**Comment by KarelCemus** [comment]
This seems to be a major work to properly support named caches. It basically requires a major redesign of the configuration and binding. I'll do it, have already started, but it will probably take some time. I'll keep you in the loop. Would it work for you?

**Comment by rval** [comment]
Absolutely, that's great! I really appreciate the quick responses. I'd be happy to take a run at this too, so please do let me know if I can help in any way.

**Comment by checat** [comment]
As a bare minimum I would suggest the implementation that does not require redesign:
- by default, only unnamed bindings are created, so new version will be compatible with current
- add a String (or list of String) option to create named bindings with that name
- add a Boolean option to disable creation of unnamed bindings

This way, only one underlying instance will be bound, as currently. But this change will allow to co-exist with EhCache or other cache implementation, and will allow to choose which data are cached locally and which in Redis.

**Comment by KarelCemus** [comment]
That's a valid point, thanks. I have some refactoring already in progress and it looks good. However, if l get stuck or short on time I fallback to your proposal to publish something soon. Would it work for you?
