### ISSUE TITLE
Move the documentation into multiple Wiki pages

### ISSUE THREAD

**Issue by KarelCemus** [KarelCemus/play-redis#107]
README is now quite complex and difficult both to read and to maintain. The issue is about it decomposition and better readability.

**Comment by KarelCemus** [comment]
@pcejrowski Hi, could you please review [the wiki](https://github.com/KarelCemus/play-redis/wiki) if it is complete and understandable? Please check at least the part related to the cluster, if the intended use is fine.

@rval Hi, could you please review [the documentation](https://github.com/KarelCemus/play-redis/wiki/Configuration#named-caches) related to the named caches? Is it complete and sufficient?

**Comment by rval** [comment]
The doc looks really good. Only thing that jumped out at me a bit is this part:

> ”The configuration of instances is recursive. Everything instance-specific can be defined under the root play.cache.redis as well as locally overwritten in the configuration of the particular named instance.”

I had to read this a couple times before I was completely clear on it. Maybe something along these lines?

> “The configuration of each instance is inherited from the `play.cache.redis` configuration. Inherited values may be overridden by the instance's own configuration (e.g., `play.cache.redis.instances.myNamedCacheInstance`)"

For the configuration example in that section, I'd suggest the following adjustments:

* Uncomment the `play.cache.redis.source` property, which will make its inheritance in `instances.play` more clear  (you’ve already done a good job explaining the default value of the source parameter earlier in the doc)
* Rename `instances.cluster` to `instances.myNamedCache` to provide a clear example of a custom name (and to distinguish it from the `source` key and `cluster` value, which could cause some confusion)

Please correct me if I’ve misunderstood anything. Pretty minor feedback though. Looks really good!

**Comment by pcejrowski** [comment]
Hey Karel, 
I like the Wikis. However, I would provide some changes, listed here:

- Configuration / Standalone vs. Cluster: it's outside of Wikis scope, but still default database is 1, which might be confusing comparing with the Redis default DB equal 0. I think we discussed that, but I don't remember the outcome
- Configuration / Standalone vs. Cluster: you define a database as null for cluster definitions, which for a cluster is not supported; it's always 0. 
- I'd write a little bit more about changes motivation in Migration Guide because you didn't an awesome job and it should be emphasized more :).

I will read it one more time during the weekend, but I think it's definitely releasable +1

**Comment by KarelCemus** [comment]
Thank you both for the review, I very appreciate it! I adjusted the wiki accordingly. 

> Configuration / Standalone vs. Cluster: it's outside of Wikis scope, but still default database is 1, which might be confusing comparing with the Redis default DB equal 0. I think we discussed that, but I don't remember the outcome

You are right, we did but neither do I remember the outcome. Though I changed the default from 1 to 0 and updated the migration guide. Should be correct right now, I hope.

> Configuration / Standalone vs. Cluster: you define a database as null for cluster definitions, which for a cluster is not supported; it's always 0.

Oh, I didn't know. So ... Can I safely remove the database configuration in the cluster? And set it always to 0? And what about the password? Is that supported or can I remove it also?

> I'd write a little bit more about changes motivation in Migration Guide because you didn't an awesome job and it should be emphasized more :).

Thanks :-) Do you have any proposals what is missing? I did it basically because of named caches because it was very difficult and hack-ish to support them in the 1.x.x, that's the motivation. The rest is just side-effect.

**Comment by KarelCemus** [comment]
@pcejrowski I really like your proposition, thanks!
