### ISSUE TITLE
Play 2.4

### ISSUE THREAD

**Issue by KarelCemus** [KarelCemus/play-redis#11]
Play 2.4 changed API

**Comment by neilchaudhuri** [comment]
Will this plugin be available for Play 2.4 anytime soon?

**Comment by KarelCemus** [comment]
Yes, it's on my roadmap, hopefully I'll get there soon (month or so). However, it should be still usable with 2.4 as it has backward compatibility with 2.3 plugins.

**Comment by KarelCemus** [comment]
@neilchaudhuri Hi, the plugin now fully implements Play 2.4.x but it is incompatible with the previous versions of Play and this plugin. There is no smooth migration. There are very significant changes, the plugin was basically rewritten from scratch as the Play's API changed very significantly.

**Comment by neilchaudhuri** [comment]
Great news. You're absolutely right. Play changed a LOT of things--surprising for a minor version upgrade. I'm sure it was a lot of work to adapt. Thanks for your hard work. Look forward to trying it out.
