### ISSUE TITLE
Using Java version of Play

### ISSUE THREAD

**Issue by limpep** [KarelCemus/play-redis#110]
Hi is it possible to use is module with with the Java version of play?

**Comment by KarelCemus** [comment]
Hi, well, this module is intended for Scala only. However:

1. it implements Play's Java Cache API, so if it is enough, than you can use it though you won't profit from the advanced functionality
2. There is common Java/Scala interoperability, but the resulting API probably is not nice as it is designed for Scala and uses Scala types.
