### ISSUE TITLE
Migration guide to 2.x.x

### ISSUE THREAD

**Issue by KarelCemus** [KarelCemus/play-redis#116]
- [x] Write a migration guide for the configuration update
- [ ] implement deprecation warning when some old unused configuration keys exist

**Comment by KarelCemus** [comment]
@rval Hi, can I ask you to review [the changelog](https://github.com/KarelCemus/play-redis/blob/master/CHANGELOG.md#link-200), especially the [Migration Guide](https://github.com/KarelCemus/play-redis/wiki/Migration-Guide#migration-from-16x-to-20x)? Is it understandable, complete, and sufficient? Or can you see anything to add or improve? Thanks

**Comment by rval** [comment]
Both look good to me! Just looks like there might be a missing word here:

> "...`source`, `timeout`, `dispatcher`, and `recovery` defines defaults and [may] be locally overwritten within each named cache configuration."

(Also I suppose "defines" should be "define")

**Comment by KarelCemus** [comment]
Great, thanks for your review! Fixed.
