### ISSUE TITLE
Active redis only on production mode

### ISSUE THREAD

**Issue by tzimisce012** [KarelCemus/play-redis#131]
As you say in your Readme, the RedisModule is not enabled by default. This could allow to activate it only on production mode and leave ehcache (for example) on dev mode. Is there any "easy" way to do this on play configuration?

This is not really a bug, just a question :full_moon_with_face: 

### Reporting a bug?
1. Version of play-redis 1.6.1
1. Version of Scala 2.12
1. Version of Play 2.6.6
1. Describe the environment if applies (usually in cloud etc.) cloud

**Comment by KarelCemus** [comment]
Hi, welcome here. What about [production configuration](https://www.playframework.com/documentation/2.6.x/ProductionConfiguration) in Play's documentation? I believe this is what you need. There is no other simpler solution. Does is answer your question? Please, let me know so I could close this issue.

**Comment by tzimisce012** [comment]
This solves my question. I was just wondering if you had some kind of internal configuration to choose the implementation dynamically. 

Thanks

**Comment by KarelCemus** [comment]
I am sorry, there is no such configuration. What would you expect? The only thing, which seems reasonable, is to dynamically disable the module, i.e., something like `play.cache.redis.enable=${redis}` and you can set it to `true` through the environment variable. However, I'm not sure if this is a good approach. I believe that when you need a different configuration for production and for development environments then you usually end up with multiple configuration files, which solves this issue pretty nicely.

**Comment by KarelCemus** [comment]
The thing is that the modules (redis, ehcache and others) are absolutely independent so there is no way to simplify the configuration and the switch. You'd need a module depending on these and possibly also other modules and providing the configuration mechanism you are looking for. And as this module would have to depend on those modules, this solution wouldn't be much generic (read widely used).

**Comment by tzimisce012** [comment]
Definitely your approach is correct.  I was not expecting nothing else, I just wanted to be sure which one was your solution.
