### ISSUE TITLE
No implementation for play.api.cache.AsyncCacheApi was bound

### ISSUE THREAD

**Issue by Enalmada** [KarelCemus/play-redis#135]
I am trying to update my play 2.6.7 project (scala 2.12.4) from play-redis 1.6.1 to 2.0.0 and getting a "No implementation for play.api.cache.AsyncCacheApi was bound" error at runtime.

> 1) No implementation for play.api.cache.AsyncCacheApi was bound.
>   while locating play.api.cache.AsyncCacheApi
>     for the 1st parameter of com.mohiva.play.silhouette.impl.util.PlayCacheLayer.<init>(PlayCacheLayer.scala:32)
>   at modules.SilhouetteModule.configure(SilhouetteModule.scala:53) (via modules: com.google.inject.util.Modules$OverrideModule -> modules.SilhouetteModule)

Here is a silhouette sample project that is working with 1.6.1 that shows the issue when upping the play-redis version to 2.0.0 and trying to run:  
https://github.com/Enalmada/play-silhouette-seed

Here is the line in question:
```
class SilhouetteModule extends AbstractModule with ScalaModule {
  def configure(): Unit = {
    bind[CacheLayer].to[PlayCacheLayer]
    ...
}
```

Could you advise what play/silhouette/redis users should be doing to update to get 2.0.0 working?

Thanks,
Adam

**Comment by KarelCemus** [comment]
Hi, oh, that sounds bad. I hope there is not any major bug in that release. I'll look at it first thing tomorrow.

**Comment by KarelCemus** [comment]
Hi Adam, 

thanks for your contribution. I have to apologize, it turned out I forgot to register `AsynchCacheApi` into binding configuration. I am releasing `2.0.1` version.
