### ISSUE TITLE
custom recovery policy override recoveryPolicyResolver example

### ISSUE THREAD

**Issue by Enalmada** [KarelCemus/play-redis#137]
Can you add an explicit example of how to migrate custom recovery policy to 2.x.x?   I used to have "play.cache.redis.recovery = custom" in my application.conf and then I created a CustomRecoveryPolicy extending RecoverWithDefault and it worked great.   Now I do see in the migration guide I should override recoveryPolicyResolver but I can't figure out how to actually do it successfully...all my attempts at overriding recoveryPolicyResolver give me messages like this:

> No implementation for play.api.cache.redis.RecoveryPolicy annotated with @com.google.inject.name.Named(value=CustomRecoveryPolicy) 

I have no doubt I am doing something silly but am stuck on it.  I would really appreciate an explicit example of how to get a working custom policy migrated from 1.x to 2.x.

**Comment by KarelCemus** [comment]
My apology, the migration guide is obviously a bit misleading at this point. This applies only to compile-time dependency injection. I'll update it. 

To have this working properly just register your class as named `RecoveryPolicy` trait.

Your custom policy:

```scala
class MyPolicy extends RecoveryPolicy {
  def recoverFrom[ T ]( rerun: => Future[ T ], default: => Future[ T ], failure: RedisException ) = default
}
```

The module:

```scala
import play.api.cache.redis.RecoveryPolicy
import play.api.inject._
import play.api.{Configuration, Environment}

class ApplicationModule extends Module {

  def bindings( environment: Environment, configuration: Configuration ) = Seq(
    // "custom" is the name in the configuration file
    bind[ RecoveryPolicy ].qualifiedWith( "custom" ).to( classOf[ MyPolicy ] )
  )
}
```

To understand the implementation, see [the default resolver](https://github.com/KarelCemus/play-redis/blob/master/src/main/scala/play/api/cache/redis/RecoveryPolicy.scala#L187) used with runtime DI.

**Comment by Enalmada** [comment]
Ok!  That was just what I needed.  Creating and registering a module like the example above seems to be working.

**Comment by KarelCemus** [comment]
For the future reference: Clarified migration guide (added headings) and extended Recovery Policy [documentation](https://github.com/KarelCemus/play-redis/wiki/Configuration#recovery-policy).
