### ISSUE TITLE
Documentation: Getting started

### ISSUE THREAD

**Issue by KarelCemus** [KarelCemus/play-redis#139]
When I was implementing an example to illustrate one of the possible uses of this module, I had to look up something in the documentation. Then I realized that the current documentation is very difficult to read and poorly structured for beginners and simple scenarios. It is very unfriendly to new users. There are elaborated some complex scenarios but the hello world, tutorial, etc. are either missing or hard to understand.

Please, help me propose readable and working documentation for beginners to ease their lives and to attract them to this project.

**I'd really appreciate some help**, so please feel free to help me and tell me:

- what information you were missing when you started using this project
- what information would you appreciate
- or even propose a structure, example, text etc.

This is what I have in mind right now:

- write a simple `where to start` into README to reduce initial barrier. Right now, there is basically nothing, which doesn't seem right
- create a tutorial, either step-by-step or just some example application with and publish its code here on GitHub

I'll keep this issue opened for some time to attract some contributors

Thanks in advance for all kinds of help and contribution
  
**UPDATE Jan 14 2017:** I started [a new project with play-redis samples](https://github.com/KarelCemus/play-redis-samples). I'd appreciate all your feedback. If there is something missing or any other example you are looking for, please, let me know.

Thanks

**Comment by sfelt-carecloud** [comment]
Hello Karel,  
Could add the example that you created for the controllers w/ the ehcache and redis enabled?  That was the only missing piece for me.  I REALLY appreciate your time, help and responsiveness to the community.  The only other documentation that might help someone are examples of binding w/ the RedisInstance for standalone and cluster.  You got me pointed in the correct direction but the docs did not point me in the correct direction.

Steve

**Comment by KarelCemus** [comment]
I started [a new project with play-redis samples](https://github.com/KarelCemus/play-redis-samples). Could you review them and give me some feedback if something is missing or there is anything else you'd appreciate?

Thanks

**Comment by KarelCemus** [comment]
I extended the README in the repository root. Now it lists the features, provides more links to the documentation and references the sample projects.

Hope it helps

**Comment by francjohny** [comment]
@KarelCemus Would really appreciate some help on setting up master and slaves nodes for replication.

**Comment by KarelCemus** [comment]
@francjohny I'm sorry, this would be out of the scope of this project. For information and tutorials regarding the redis configuraiton see the documentation of the [redis database](https://redis.io/).

**Comment by francjohny** [comment]
Thanks @KarelCemus. I will check out more resources.

**Comment by KarelCemus** [comment]
As there are no requests for documentation improvement, I'm closing this ticket for now. It seems the current documentation including the samples is sufficient.

If there are some new ideas to improve the documentation, feel free to share them.
