### ISSUE TITLE
Timeouts

### ISSUE THREAD

**Issue by tzimisce012** [KarelCemus/play-redis#147]
So I am getting the following behavior. I have my play 2.6.10 web service using the Java AsyncCache Api with play-redis 2.0.2 When redis is online, everything works great, but if I disconnect Redis, my web service is reacting really slow. 

With the method `getOrElseUpdate`, looks like we try to make a get, check that we do not have connection, do the callable, try to make a set with the result, ask again for the connection and finally return the result... This might delay the response in 3 seconds so far. Is this the expected behavior for this implementation?

**Comment by KarelCemus** [comment]
Well, this is tough to say. I see your point but I believe that this would need the support by rediscala itself. It seems to be related to these:

- https://github.com/etaty/rediscala/issues/57
- https://github.com/etaty/rediscala/issues/72

However, it seems there is no support for a timeout and providing own wrapper may result in resource leakage, as it pointed out in one of the comments.

I'll think about it but I'm not sure how to deal with it. I see strong points on both sides.

Do you have any proposition?

**Comment by tzimisce012** [comment]
Actually, I don't know if what I need is timeout support. I believe that if I don't have connection with Redis, when I do `getOrElseUpdate` I should do the callable directly instead of trying to GET, trying to reconnect, callable, SET, trying to reconnect, return the result.

**Comment by KarelCemus** [comment]
Yes, this is one of the possible implementations of your proposal - eagerly "fail" when the instance is disconnected. Question is, what if there is no connection due to some idle timeout? (don't know if exists)

And still, this would cover only some cases. When the connection is officially active but the response takes a while, it would be still slow.

By the way, see [this](https://github.com/KarelCemus/play-redis/wiki/How-to-Use#eager-and-lazy-invocation), it should remove the timeout on the `set` part.

**Comment by tzimisce012** [comment]
About the idle timeouts, redis uses TCP connections, and the timeouts of them can be configured on your operative system or your container...

If Redis is just working slowly, I don't think we can do too much since the rediscala does not give support for timeouts. 

I will check the eager implementation that you offer

**Comment by tzimisce012** [comment]
Hi. I have been checking the eager implementation for the set part and this will help to the performance of my web service, but I am not sure how to use it on Java. Can I use it with `getOrElseUpdate`?

**Comment by KarelCemus** [comment]
Interesting question. I'd have to check it, but I think it's not supported as it uses Scala implicits, and I am not sure how to bring a similar easy to use solution to Java

**Comment by KarelCemus** [comment]
This issue actually opens two tasks:

- [ ] support of eager and lazy invocation in Java
- [ ] eagerly fail the request when the connection is not established

**Comment by tzimisce012** [comment]
Agreed. My idea was to PR the support of eager and lazy invocation in Java but I was sort of busy during this week. I'll try again in the new a week :)

**Comment by KarelCemus** [comment]
It seems I've figured out the solution, I'll submit a PR and ask you for the review if you are willing to do it.

**Comment by KarelCemus** [comment]
In `2.1.0`, there is introduced optional timeout on each request, disabled by default.
