### ISSUE TITLE
Make setIfNotExists atomic?

### ISSUE THREAD

**Issue by jgdodson** [KarelCemus/play-redis#156]
I was looking over [the redis docs](https://redis.io/commands/set) and saw that since redis 2.6.12, it has been possible to SET with both an existence condition (if-not-exists or only-if-exists) *and* and expiry time (with millisecond resolution). Would this not allow the implementation of setIfNotExists to be made atomic?

**Comment by KarelCemus** [comment]
You mean changing [this implementation](https://github.com/KarelCemus/play-redis/blob/ba27667b5a6321b6e7314f4b413810d20e5d104d/src/main/scala/play/api/cache/redis/connector/RedisConnectorImpl.scala#L84) to SET instead of SETNX?

**Comment by jgdodson** [comment]
Yes to using SET (with the NX option) instead of SETNX (which the docs warn may be deprecated one day). However, the real optimization would be to also use the EX option of SET instead of the expire() command. This would allow [this implementation](https://github.com/KarelCemus/play-redis/blob/427889d881fe0c856348131301bc510e46f64c08/src/main/scala/play/api/cache/redis/impl/RedisCache.scala#L30) to be changed so that it makes only one call to the connector (hence atomic). The connector method would need a new parameter for the expire duration.

**Comment by jgdodson** [comment]
Awesome! Thanks for working on this.
