### ISSUE TITLE
how to use it with java?

### ISSUE THREAD

**Issue by ferdavs** [KarelCemus/play-redis#160]
play version 2.6.13

**Comment by KarelCemus** [comment]
This is too wide question. Please, use the issue tracking for bugs or feature requests.

See the [documentation](https://github.com/KarelCemus/play-redis/wiki), which includes list of APIs and the integration guide. The play-redis implements standard Java cache APIs thus you use it just like the EhCache.

**Comment by ferdavs** [comment]
I am getting this exception 
**java.io.NotSerializableException: No configured serialization-bindings for class [com.fasterxml.jackson.databind.node.ObjectNode]**

I am trying to cache Result object with json in the body.

**Comment by KarelCemus** [comment]
Play-redis uses Akka serialization to serialize data to redis natives (basically primitive values). Result object is not a primitive thus it has to be either `java.io.Serializable` which is not, or you have to implement some other serializer.

See [Akka documentation](https://doc.akka.io/docs/akka/2.5.4/scala/serialization.html) for serialization to understand and define a serializer.

See [play-redis limitations](https://github.com/KarelCemus/play-redis/wiki/How-to-Use#limitations) to understand serialization limitations by the play-redis.

Or cache the json (as a `String`!!!) not the `Result`
