### ISSUE TITLE
get existing redis client to access rediscala api

### ISSUE THREAD

**Issue by rolandjohann** [KarelCemus/play-redis#167]
Is there a way to get the underlying `rediscala` client to be able to use the complete set of its API in addition to the convenient API of the caches?

**Comment by KarelCemus** [comment]
Not through play-redis. There's no point in exposing the underlying client. However, you can freely create another instance of `RedisCommands` and use it as you want at the cost of one additional connection to redis server, which seems fine to me.

**Comment by rolandjohann** [comment]
Thanks for the quick answer

**Comment by sim-jac** [comment]
@KarelCemus : Can you maybe provide an example on how this can be implemented? I need a SortedSet Implementation and do not want to change the redis library because we like the ease usage.

We are still using the Scala-Api in Java without any problems!

Thanks & best regards
Simon

**Comment by KarelCemus** [comment]
@sim-jac I am not sure what's on your mind and what you are trying to achieve. However, check it [here](https://github.com/KarelCemus/play-redis/blob/master/src/main/scala/play/api/cache/redis/connector/RedisCommands.scala#L61) to get the idea of creating a custom instance of the internal rediscala. While this opens another connection, you are free to use it wherever you like.

```scala

import redis.RedisClient

val client = new RedisClient(
  host = host,
  port = port,
  db = database,
  password = password
)
```

Then you can directly use it. I'd even suggest to encapsulate it into a `javax.inject.Provider` to have it available via dependency injection, which would significantly ease your use.

**Comment by sim-jac** [comment]
@KarelCemus : Thanks for the fast and great reply!

I need access to the SortedSet commands in redis to implement a sorted, unique list. And because we are using your plugin for the list and map handling with ease I don't want to replace it with something like jedis.

Unfortunately it is very hard for me to read scala code and I don't fully get how to access the RedisClient.

I could create and map the scala-attributes of the client in Java:
 
```
String host = config.getString("play.cache.redis.host");
Option<String> pw = Option.apply(config.getString("play.cache.redis.password"));
Option<Object> db = Option.apply(config.getInt("play.cache.redis.database"));
int port = config.getInt("play.cache.redis.port");
        
Option<FiniteDuration> timeout = Option.empty();
var dispatcher = new RedisDispatcher("my.rediscala.rediscala-client-worker-dispatcher");
        
this.client = new RedisClient(host, port, pw, db, "My-Connection", timeout, system, dispatcher);

```


But I could not achieve how to send the commands (which are defined in redis.commands.Set?) to the connection. Maybe you have another hint for me?


Thanks and best regards
Simon

**Comment by KarelCemus** [comment]
First of all, if there is anything you miss in the play redis, feel free to propose a new feature.

Second, I don't see your problem since the client you created in `this.client` transitively implements `redis.commands.Sets`. Therefore, just call `this.client.scard("my-key")` and you are done.
