### ISSUE TITLE
No Connection established

### ISSUE THREAD

**Issue by Enalmada** [KarelCemus/play-redis#174]
When I make a code change and reload my browser, I notice that when the application comes back again and tries to hit the cache right away, there more often than not a "No Connection established" error.  I can see that there is always a console log message before it implying the cache is started and connected.  It is almost like redis cache actor says it is connected and returns to play before it is actually ready to handle connections.

play-redis: 2.1.2
Scala: 2.12.6
Play: 2.6.15
SyncCacheApi

Setting the following timeouts don't seem to have any impact:
play.cache.redis.sync-timeout=10s
play.cache.redis.redis-timeout=10s
It isn't waiting 10 seconds to respond.

I have only noticed this in dev mode first thing after recompilation cycle.  Is there something more that play-redis can be doing to confirm it is actually connected before trying to fetch from cache after startup?

```
[info] Done compiling.

--- (RELOAD) ---

14:28:14 INFO  play.api.cache.redis - Stopping the redis cache actor ...
14:28:14 INFO  play.api.cache.redis - Redis cache stopped.
14:19:13 INFO  play.api.cache.redis - Redis cache actor started. It is connected to localhost:6379?database=0
14:19:13 INFO  play.api.Play - Application started (Dev)
14:19:14 WARN  application - failure: play.api.cache.redis.ExecutionFailedException: Execution of 'GET' for key 'hasFlags.17592186045482' failed
14:19:14 ERROR play.api.cache.redis - Command GET for key 'hasFlags.17592186045482' failed.
redis.actors.NoConnectionException$: No Connection established
        at redis.actors.NoConnectionException$.<clinit>(RedisClientActor.scala)
        at play.api.cache.redis.connector.RequestTimeout$.$anonfun$fail$1(RequestTimeout.scala:28)
        at akka.pattern.FutureTimeoutSupport.liftedTree1$1(FutureTimeoutSupport.scala:25)
        at akka.pattern.FutureTimeoutSupport.$anonfun$after$1(FutureTimeoutSupport.scala:25)
        at akka.actor.Scheduler$$anon$4.run(Scheduler.scala:140)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

14:19:20 DEBUG application - hasFlags cache hit success
```

**Comment by KarelCemus** [comment]
>  It is almost like redis cache actor says it is connected and returns to play before it is actually ready to handle connections.

Basically, you are right. It seems there is no way to check the connection is really established with the `rediscala`. In consequence, the message is logged when the actor is created, not connected. 

However, the implementation of the actor should have a queue and should be ready for receiving requests even when it is not connected. It's odd that it throws the exception. It browsed the code and the only thing, which seems likely to cause the exception, is [this](https://github.com/KarelCemus/play-redis/blob/41782a4c31681da0351dfc2c08ddc2b79fe3f1f4/src/main/scala/play/api/cache/redis/connector/RequestTimeout.scala#L54). If the connection is not established within 300 millis, then it fails. Could it be the issue?

Unfortunately, I cannot figure out any simple way to test it and verify that increasing the timeout would help. The only solution I have in mind is to make the timeout configurable but it is "a lot of work", which doesn't have to help.

**Comment by Enalmada** [comment]
Yes, I believe you found it.  When I change that 300.millis to 300.seconds, I can't seem to reproduce the issue.  What is the disadvantage of having a long timeout there?

**Comment by KarelCemus** [comment]
That is good news that we've the cause.

The idea behind the cache is that the cache should be quick and transparent. In consequence, when the redis is down or slow, it should be better to disable the cache and compute the value instead. This timeout puts the threshold when the response is "quick enough" and when it is "too late". 

Setting the timeout too high practically disables this feature - when the redis goes down, the requests are still waiting for the response "infinitely" and thus the requests stuck. You can consider setting this value to 1-2 seconds at most I think but still then the response would be quite slow.

Regarding this issue, I can make the timeout configurable and leave the decision to developers, if you agree.

**Comment by KarelCemus** [comment]
Looking at the code, the timeout applies only when the connection is not established. When it is established, it is not considered, thus working but slow requests pass through. So we talk only about the situation when the connection is not established, which happens during the start up or when the redis goes down while the application is running.

**Comment by Enalmada** [comment]
Ok, that is good news.  That means it could be low risk to have a very generous timeout value there and not bother about it being configurable.
