### ISSUE TITLE
Is Disabling Ehcache Module OK?

### ISSUE THREAD

**Issue by neilchaudhuri** [KarelCemus/play-redis#19]
Quick question.

Just saw this in the Play documentation:

"*Note: If you are working on a library, it is highly discouraged to use play.modules.disabled to disable modules, as it can lead to undetermistic results when modules are loaded by the application (see [this issue](https://github.com/playframework/play-slick/issues/245) for reasons on why you should not touch play.modules.disabled). In fact, play.modules.disabled is intended for end users to be able to override what modules are enabled by default.*"

I know you have unit tests supporting your approach, but I just wanted to bring this to your attention in case you hadn't seen it. It is buried in Play's documentation.

Thanks.

**Comment by KarelCemus** [comment]
Oh I didn't know that. This is probably new, with plugins there was a different mechanism and I poorly migrated it. Thanks, I'll fix it.

**Comment by KarelCemus** [comment]
Fixed, see README for changes and how to enable/disable the module
