### ISSUE TITLE
Error during creating and/or bounding bean of named cache in sentinel mode

### ISSUE THREAD

**Issue by pavlod-egnaroinc** [KarelCemus/play-redis#190]
Version of play-redis: 2.3.0
Version of Java: 8
Version of Play: 2.6.12
Describe the environment if applies (usually in cloud etc.): Docker
Describe the expected behavior:
Named caches provided in redis config (in sentinel mode) should be bounded to specific beans.
Describe the actual behavior, follow the same scenario:
The named cache does not bounding and throwing the following exception:
[https://pastebin.com/dW0VFNZ4](https://pastebin.com/dW0VFNZ4)

Provide instructions to reproduce the issue:
The redis.conf file:
```
play.modules.disabled += "play.api.cache.ehcache.EhCacheModule"
play.modules.enabled += "play.api.cache.redis.RedisCacheModule"

play.cache.redis {
 
  # source property; standalone is default
  source: sentinel
 
  default-cache: "ContainerMgr"
  master-group: "r0"
  sentinels: [
    {
      host: redis.marathon.l4lb.thisdcos.directory,
      port: 26379
    }
  ]
}
```
We have 3 sentinel instances launched in the same containers that slaves and master in DCOS under single endpoint

The service where the named cache supposed to be injected:
 ```
    private final SyncCacheApi cache;
 
    @Inject
    public AppFactory(@Named("ContainerMgr")SyncCacheApi containerCache) {
        this.cache = containerCache;
    }
```

**Comment by KarelCemus** [comment]
Not an issue, this changed in 2.1.0. See [Changelogfor details](https://github.com/KarelCemus/play-redis/blob/master/CHANGELOG.md#removal-of-named-and-introduction-of-namedcache)

For future reference, use `@NamedCache` instead of `@Named`
