### ISSUE TITLE
support enumerate keys by a pattern

### ISSUE THREAD

**Issue by pangwa** [KarelCemus/play-redis#192]
Is it possible to provide an api to enumerate keys in redis following a pattern?

I need to migrate some legacy keys to use a new value. it would be nice if we can support in the cache api.

**Comment by KarelCemus** [comment]
I believe there already exists [`CacheApi.matching`](https://github.com/KarelCemus/play-redis/blob/master/src/main/scala/play/api/cache/redis/CacheApi.scala#L84), which should be what you are looking for. In case it is not, could you elaborate your suggestion into more details?

**Comment by pangwa** [comment]
Thanks, this api is enough for my use case!
