### ISSUE TITLE
Advanced CacheAPI for Java

### ISSUE THREAD

**Issue by ourgit** [KarelCemus/play-redis#206]
as you documented, play-redis implements advanced redis feather in scala,but java not,could you please implement those under java? Thank you very much.

**Comment by KarelCemus** [comment]
I am sorry since I don't use Play with Java, I don't intend to do it myself due to limited time capacity. However, I am willing to accept a PR and maintain it. 

Are you willing to implement it?

**Comment by ourgit** [comment]
@KarelCemus Hi Karel,
I am sorry for late response, I am too busy to code recently. I am update reposity to  "com.github.karelcemus" %% "play-redis" % "2.5.0", but i don't find any new advanced feather there.
For your converience,i post some screenshot here. Thank you.
```   @Inject
    AsyncCacheApi cache;```

![image](https://user-images.githubusercontent.com/714359/58682933-1237cc80-83a5-11e9-9cd8-dfbfaaf5a2b4.png)

or 

```   @Inject
    SyncCacheApi cache;```
![image](https://user-images.githubusercontent.com/714359/58682951-1ebc2500-83a5-11e9-8b4d-03f62d32b0d3.png)

**Comment by KarelCemus** [comment]
Version `2.5.0` is not released yet, this is only PR.

Therefore to use this version, you have to:

1. checkout this repo
2. checkout branch `206-advanced-java-api`
3. run `sbt publishLocal`
4. and then use `2.5.0-SNAPSHOT` version in your project

**Comment by ourgit** [comment]
@KarelCemus 
Hi Karel,
I have try your method, but sbt only output  2.4.1-SNAPSHOT

here is the details:
`

Administrator@PC-20190225ZLZV MINGW64 /e/projects/7-github/play-redis (206-advan                                            ced-java-api)                                                                                                               $ sbt publishLocal                                                                                                          [info] Loading settings for project play-redis-build from plugins.sbt,sonatype.s                                            bt ...                                                                                                                      [info] Loading project definition from E:\projects\7-github\play-redis\project                                              [info] Updating ProjectRef(uri("file:/E:/projects/7-github/play-redis/project/")                                            , "play-redis-build")...                                                                                                    [info] downloading https://repo1.maven.org/maven2/org/scoverage/sbt-coveralls_2.                                            12_1.0/1.2.2/sbt-coveralls-1.2.2.jar ...                                                                                    [info] downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.g                                            ithub.gseitz/sbt-release/scala_2.12/sbt_1.0/1.0.11/jars/sbt-release.jar ...                                                 [info] downloading https://repo1.maven.org/maven2/org/scoverage/sbt-scoverage_2.                                            12_1.0/1.5.1/sbt-scoverage-1.5.1.jar ...                                                                                    [info] downloading https://repo1.maven.org/maven2/net/virtual-void/sbt-dependenc                                            y-graph_2.12_1.0/0.9.0/sbt-dependency-graph-0.9.0.jar ...                                                                   [info]  [SUCCESSFUL ] org.scoverage#sbt-scoverage;1.5.1!sbt-scoverage.jar (1731m                                            s)                                                                                                                          [info] downloading https://repo1.maven.org/maven2/org/scalariform/sbt-scalarifor                                            m_2.12_1.0/1.8.2/sbt-scalariform-1.8.2.jar ...                                                                              [info]  [SUCCESSFUL ] org.scoverage#sbt-coveralls;1.2.2!sbt-coveralls.jar (2645m                                            s)                                                                                                                          [info] downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.j                                            suereth/sbt-pgp/scala_2.12/sbt_1.0/1.1.2/jars/sbt-pgp.jar ...                                                               [info] downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.t                                            imushev.sbt/sbt-updates/scala_2.12/sbt_1.0/0.4.0/jars/sbt-updates.jar ...                                                   [info]  [SUCCESSFUL ] org.scalariform#sbt-scalariform;1.8.2!sbt-scalariform.jar                                             (1170ms)                                                                                                                    [info] downloading https://repo1.maven.org/maven2/org/scoverage/scalac-scoverage                                            -plugin_2.12/1.3.1/scalac-scoverage-plugin_2.12-1.3.1.jar ...                                                               [info] downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.j                                            suereth/pgp-library_2.12/1.1.2/jars/pgp-library_2.12.jar ...                                                                [info]  [SUCCESSFUL ] net.virtual-void#sbt-dependency-graph;0.9.0!sbt-dependency                                            -graph.jar (5767ms)                                                                                                         [info] downloading https://repo1.maven.org/maven2/com/fasterxml/jackson/module/j                                            ackson-module-scala_2.12/2.9.0/jackson-module-scala_2.12-2.9.0.jar ...                                                      [info]  [SUCCESSFUL ] com.fasterxml.jackson.module#jackson-module-scala_2.12;2.9                                            .0!jackson-module-scala_2.12.jar(bundle) (1127ms)                                                                           [info] downloading https://repo1.maven.org/maven2/org/eclipse/jgit/org.eclipse.j                                            git/3.7.0.201502260915-r/org.eclipse.jgit-3.7.0.201502260915-r.jar ...                                                      [info]  [SUCCESSFUL ] org.scoverage#scalac-scoverage-plugin_2.12;1.3.1!scalac-sc                                            overage-plugin_2.12.jar (4519ms)                                                                                            [info] downloading https://repo1.maven.org/maven2/org/scalaj/scalaj-http_2.12/2.                                            3.0/scalaj-http_2.12-2.3.0.jar ...                                                                                          [info]  [SUCCESSFUL ] com.github.gseitz#sbt-release;1.0.11!sbt-release.jar (7692                                            ms)                                                                                                                         [info] downloading https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jac                                            kson-databind/2.9.0/jackson-databind-2.9.0.jar ...                                                                          [info]  [SUCCESSFUL ] com.jsuereth#sbt-pgp;1.1.2!sbt-pgp.jar (8891ms)                                                       [info] downloading https://repo1.maven.org/maven2/com/fasterxml/jackson/module/j                                            ackson-module-paranamer/2.9.0/jackson-module-paranamer-2.9.0.jar ...                                                        [info]  [SUCCESSFUL ] com.jsuereth#pgp-library_2.12;1.1.2!pgp-library_2.12.jar (                                            6256ms)                                                                                                                     [info] downloading https://repo1.maven.org/maven2/com/thoughtworks/paranamer/par                                            anamer/2.8/paranamer-2.8.jar ...                                                                                            [info]  [SUCCESSFUL ] org.eclipse.jgit#org.eclipse.jgit;3.7.0.201502260915-r!org                                            .eclipse.jgit.jar (2762ms)                                                                                                  [info] downloading https://repo1.maven.org/maven2/com/googlecode/javaewah/JavaEW                                            AH/0.7.9/JavaEWAH-0.7.9.jar ...                                                                                             [info]  [SUCCESSFUL ] com.googlecode.javaewah#JavaEWAH;0.7.9!JavaEWAH.jar(bundle                                            ) (850ms)                                                                                                                   [info] downloading https://repo1.maven.org/maven2/org/apache/httpcomponents/http                                            client/4.1.3/httpclient-4.1.3.jar ...                                                                                       [info]  [SUCCESSFUL ] com.thoughtworks.paranamer#paranamer;2.8!paranamer.jar(bun                                            dle) (1692ms)                                                                                                               [info] downloading https://repo1.maven.org/maven2/org/apache/httpcomponents/http                                            core/4.1.4/httpcore-4.1.4.jar ...                                                                                           [info]  [SUCCESSFUL ] org.scalaj#scalaj-http_2.12;2.3.0!scalaj-http_2.12.jar (33                                            49ms)                                                                                                                       [info] downloading https://repo1.maven.org/maven2/commons-codec/commons-codec/1.                                            4/commons-codec-1.4.jar ...                                                                                                 [info]  [SUCCESSFUL ] com.fasterxml.jackson.module#jackson-module-paranamer;2.9.                                            0!jackson-module-paranamer.jar(bundle) (1995ms)                                                                             [info] downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.d                                            wijnand/sbt-compat/scala_2.12/sbt_1.0/1.1.0/jars/sbt-compat.jar ...                                                         [info]  [SUCCESSFUL ] org.apache.httpcomponents#httpclient;4.1.3!httpclient.jar                                             (1397ms)                                                                                                                    [info] downloading https://repo1.maven.org/maven2/org/scalariform/scalariform_2.                                            12/0.2.5/scalariform_2.12-0.2.5.jar ...                                                                                     [info]  [SUCCESSFUL ] commons-codec#commons-codec;1.4!commons-codec.jar (2016ms)                                            [info]  [SUCCESSFUL ] org.apache.httpcomponents#httpcore;4.1.4!httpcore.jar (305                                            3ms)                                                                                                                        [info]  [SUCCESSFUL ] com.dwijnand#sbt-compat;1.1.0!sbt-compat.jar (2900ms)                                                 [info]  [SUCCESSFUL ] org.scalariform#scalariform_2.12;0.2.5!scalariform_2.12.ja                                            r (8882ms)                                                                                                                  [info]  [SUCCESSFUL ] com.timushev.sbt#sbt-updates;0.4.0!sbt-updates.jar (31155m                                            s)                                                                                                                          [info]  [SUCCESSFUL ] com.fasterxml.jackson.core#jackson-databind;2.9.0!jackson-                                            databind.jar(bundle) (35910ms)                                                                                              [info] Done updating.                                                                                                       [warn] There may be incompatibilities among your library dependencies; run 'evic                                            ted' to see detailed eviction warnings.                                                                                     [info] Compiling 3 Scala sources to E:\projects\7-github\play-redis\project\targ                                            et\scala-2.12\sbt-1.0\classes ...                                                                                           Waiting for lock on C:\Users\Administrator\.ivy2\.sbt.ivy.lock to be available..                                            .                                                                                                                           [info] Non-compiled module 'compiler-bridge_2.12' for Scala 2.12.7. Compiling...                                            [info]   Compilation completed in 6.473s.                                                                                   [warn] there was one feature warning; re-run with -feature for details                                                      [warn] one warning found                                                                                                    [info] Done compiling.                                                                                                      [info] Loading settings for project play-redis from build.sbt,version.sbt ...                                               [info] Set current project to Redis Cache for Play (in build file:/E:/projects/7                                            -github/play-redis/)                                                                                                        [info] Scalariform auto formatting enabled                                                                                  [info] Updating ...                                                                                                         [info] Applying Scalariform preferences found in E:\projects\7-github\play-redis                                            \.\.scalariform.conf                                                                                                        [info] Packaging E:\projects\7-github\play-redis\target\scala-2.12\play-redis_2.                                            12-2.4.1-SNAPSHOT-sources.jar ...                                                                                           [info] Formatting 46 Scala sources ProjectRef(uri("file:/E:/projects/7-github/pl                                            ay-redis/"), "play-redis")(compile) ...                                                                                     [info] Wrote E:\projects\7-github\play-redis\target\scala-2.12\play-redis_2.12-2                                            .4.1-SNAPSHOT.pom                                                                                                           [info] Done packaging.                                                                                                      [info] downloading https://repo1.maven.org/maven2/com/typesafe/akka/akka-actor_2                                            .12/2.5.6/akka-actor_2.12-2.5.6.jar ...                                                                                     [info] downloading https://repo1.maven.org/maven2/org/specs2/specs2-core_2.12/4.                                            4.1/specs2-core_2.12-4.4.1.jar ...                                                                                          [info] downloading https://repo1.maven.org/maven2/org/specs2/specs2-mock_2.12/4.                                            4.1/specs2-mock_2.12-4.4.1.jar ...                                                                                          [info] downloading https://repo1.maven.org/maven2/com/typesafe/play/play-specs2_                                            2.12/2.7.0/play-specs2_2.12-2.7.0.jar ...                                                                                   [info] downloading https://repo1.maven.org/maven2/org/specs2/specs2-matcher_2.12                                            /4.4.1/specs2-matcher_2.12-4.4.1.jar ...                                                                                    [info] downloading https://repo1.maven.org/maven2/org/specs2/specs2-common_2.12/                                            4.4.1/specs2-common_2.12-4.4.1.jar ...                                                                                      [info]  [SUCCESSFUL ] com.typesafe.play#play-specs2_2.12;2.7.0!play-specs2_2.12.                                            jar (1812ms)                                                                                                                [info] downloading https://repo1.maven.org/maven2/org/specs2/specs2-fp_2.12/4.4.                                            1/specs2-fp_2.12-4.4.1.jar ...                                                                                              [info]  [SUCCESSFUL ] org.specs2#specs2-mock_2.12;4.4.1!specs2-mock_2.12.jar (26                                            92ms)                                                                                                                       [info] downloading https://repo1.maven.org/maven2/org/mockito/mockito-core/2.23.                                            4/mockito-core-2.23.4.jar ...                                                                                               [info]  [SUCCESSFUL ] org.specs2#specs2-fp_2.12;4.4.1!specs2-fp_2.12.jar (1779ms                                            )                                                                                                                           [info] downloading https://repo1.maven.org/maven2/net/bytebuddy/byte-buddy/1.9.3                                            /byte-buddy-1.9.3.jar ...                                                                                                   [info]  [SUCCESSFUL ] org.mockito#mockito-core;2.23.4!mockito-core.jar (3008ms)                                             [info] downloading https://repo1.maven.org/maven2/net/bytebuddy/byte-buddy-agent                                            /1.9.3/byte-buddy-agent-1.9.3.jar ...                                                                                       [info]  [SUCCESSFUL ] net.bytebuddy#byte-buddy-agent;1.9.3!byte-buddy-agent.jar                                             (1088ms)                                                                                                                    [info] downloading https://repo1.maven.org/maven2/org/specs2/specs2-junit_2.12/4                                            .3.6/specs2-junit_2.12-4.3.6.jar ...                                                                                        [info]  [SUCCESSFUL ] org.specs2#specs2-matcher_2.12;4.4.1!specs2-matcher_2.12.j                                            ar (7152ms)                                                                                                                 [info]  [SUCCESSFUL ] org.specs2#specs2-junit_2.12;4.3.6!specs2-junit_2.12.jar (                                            1784ms)                                                                                                                     [info]  [SUCCESSFUL ] net.bytebuddy#byte-buddy;1.9.3!byte-buddy.jar (13022ms)                                               [info]  [SUCCESSFUL ] org.specs2#specs2-common_2.12;4.4.1!specs2-common_2.12.jar                                             (32250ms)                                                                                                                  [info]  [SUCCESSFUL ] org.specs2#specs2-core_2.12;4.4.1!specs2-core_2.12.jar (46                                            042ms)                                                                                                                      [info]  [SUCCESSFUL ] com.typesafe.akka#akka-actor_2.12;2.5.6!akka-actor_2.12.ja                                            r (49343ms)                                                                                                                 [info] Done updating.                                                                                                       [info] Main Scala API documentation to E:\projects\7-github\play-redis\target\sc                                            ala-2.12\api...                                                                                                             [info] Compiling 46 Scala sources and 5 Java sources to E:\projects\7-github\pla                                            y-redis\target\scala-2.12\classes ...                                                                                       model contains 101 documentable templates                                                                                   [info] Main Scala API documentation successful.                                                                             [info] Packaging E:\projects\7-github\play-redis\target\scala-2.12\play-redis_2.                                            12-2.4.1-SNAPSHOT-javadoc.jar ...                                                                                           [info] Done packaging.                                                                                                      [info] Done compiling.                                                                                                      [info] Packaging E:\projects\7-github\play-redis\target\scala-2.12\play-redis_2.                                            12-2.4.1-SNAPSHOT.jar ...                                                                                                   [info] Done packaging.                                                                                                      [info] :: delivering :: com.github.karelcemus#play-redis_2.12;2.4.1-SNAPSHOT ::                                             2.4.1-SNAPSHOT :: integration :: Fri May 31 14:38:35 CST 2019                                                               [info]  delivering ivy file to E:\projects\7-github\play-redis\target\scala-2.12                                            \ivy-2.4.1-SNAPSHOT.xml                                                                                                     [info]  published play-redis_2.12 to C:\Users\Administrator\.ivy2\local\com.gith                                            ub.karelcemus\play-redis_2.12\2.4.1-SNAPSHOT\poms\play-redis_2.12.pom                                                       [info]  published play-redis_2.12 to C:\Users\Administrator\.ivy2\local\com.gith                                            ub.karelcemus\play-redis_2.12\2.4.1-SNAPSHOT\jars\play-redis_2.12.jar                                                       [info]  published play-redis_2.12 to C:\Users\Administrator\.ivy2\local\com.gith                                            ub.karelcemus\play-redis_2.12\2.4.1-SNAPSHOT\srcs\play-redis_2.12-sources.jar                                               [info]  published play-redis_2.12 to C:\Users\Administrator\.ivy2\local\com.gith                                            ub.karelcemus\play-redis_2.12\2.4.1-SNAPSHOT\docs\play-redis_2.12-javadoc.jar                                               [info]  published ivy to C:\Users\Administrator\.ivy2\local\com.github.karelcemu                                            s\play-redis_2.12\2.4.1-SNAPSHOT\ivys\ivy.xml                                                                               [success] Total time: 88 s, completed 2019-5-31 14:38:36
--


`

**Comment by KarelCemus** [comment]
You are right, my bad. Obviously, I forgot to increase the version. Then either use `2.4.1-SNAPSHOT` or bump it yourself in `version.sbt` file, this makes no difference to this PR

**Comment by ourgit** [comment]
@KarelCemus 
Ooops, I have try to change to version 2.4.1-SNAPSHOT before you reply,
but don't find any new advanced feather there. So I turn to the source, there is the new feather method indeed, and what should I do now？

**Comment by KarelCemus** [comment]
There exists new `play.cache.redis.AsyncCacheApi`, therefore either inject it via DI or use `javaAsync` instance in `RedisCaches`, which has now more specific interface, as is visible [here](https://github.com/KarelCemus/play-redis/pull/209/files#diff-184f42f757769b1abc43e98c38d42647R21)

**Comment by KarelCemus** [comment]
Maybe you could checkout the whole PR to see the changes and to know what is new

**Comment by ourgit** [comment]
I mean method below in AsynCacheApi.java is new/advance to me. I need those method,but i can not find there. However when I turn the inject to play.cache.redis.AsyncCacheApi, i see those advanced methods. Now,I am testing them use junit

```
setIfNotExists
setAllIfNotExist
append
expire
removeAllKeys
increment
```

**Comment by KarelCemus** [comment]
> i can not find there. However when I turn the inject to play.cache.redis.AsyncCacheApi, i see those advanced methods.

Not sure I understand. Could you be more specific? It does not work or does it?

I believe JUnit is not necessary since there is pretty good test coverage in the PR

**Comment by ourgit** [comment]
> Not sure I understand. Could you be more specific? It does not work or does it?

I mean it works!

> I believe JUnit is not necessary since there is pretty good test coverage in the PR

OK,  I will use the version in my project for some days, and report then.

**Comment by KarelCemus** [comment]
[There is the test coverage](https://github.com/KarelCemus/play-redis/pull/209/files#diff-15c84ca0a42052e782d5fcada35159d3), in case you are interested in

> OK, I will use the version in my project for some days, and report then.

Great!

**Comment by ourgit** [comment]
BTW ,why not prodive play.cache.redis.SyncCacheApi for user? SyncCacheApi is much more convenient for us. What do you think？

**Comment by KarelCemus** [comment]
Well, I'd better have tested async impl first, sync api may come later. There are some specific and additional issues, and thus it requires some additional efforts.

Anyway, Scala and Play encourages non-blocking code which has significantly greater performance and throughput, therefore I'd considered to discourage sync code by not providing the sync api. However, I'll provide it later

**Comment by ourgit** [comment]
I am no doubt that non-blocking code should excel blocking code,however if we consider the memory response ,maybe speed will be almost same, i am just guessing huh, do you test the difference between them?

**Comment by KarelCemus** [comment]
Well, I haven't conducted any tests myself, though impact of async code on resources comparing to blocking code is quite obvious. Anyway, this is my personal preference and I'll provide sync api later, when the async is tested and stable to reduce the efforts.

Since I do not use Java api at all, I try to minimize the efforts as I do it at my spare time

**Comment by ourgit** [comment]
Thank you very much!

**Comment by KarelCemus** [comment]
Any progress on the testing? How does it look? I'd like to release this feature in `2.5.0`, which will come when Play is ready for Scala 2.13

**Comment by ourgit** [comment]
So far so good. I have run the version on a small module for several weeks, it has been all right so far, if occurs some bug, i will open issue here. Thank you for the repository.

**Comment by KarelCemus** [comment]
That is great news, thanks for the update. Then I'll release the new version soon.
