### ISSUE TITLE
Platform-independent configuration

### ISSUE THREAD

**Issue by KarelCemus** [KarelCemus/play-redis#21]
> Just a small suggestion. Your classes and traits named Heroku* maybe should be renamed to something more generic like with Url* or Env*. Heroku is the cloud provider I am using, but those who deploy to other providers like Microsoft Azure may also have to deal with the same issue (configuration via url). This way it will be more intuitive that the code isn't platform-dependent but rather env var dependent. Of course this is your decision.

Well that's true but I'm not sure it would work in other envs, I haven't read their specification. There might be different env variable, no authentication etc. I considered the current impl a bit safer. But I'll think about your suggestion and possibly provide a bit more generic solution.

----

Goal is to provide more generic and configuration providers not to be platform-specific. It would be best to have configurable ENV variable, optional authentication and possibly more.

**Comment by KarelCemus** [comment]
@neilchaudhuri: Would you look at the refactored configuration in [branch 21](https://github.com/KarelCemus/play-redis/blob/21/src/main/scala/play/api/cache/redis/Configuration.scala) please? Do you consider this better fitting to more platforms including Heroku and Azure? Is it more intuitive?

Do you have any suggestions?

Thanks!

**Comment by neilchaudhuri** [comment]
Looks like you're simply asking for the name of the environment variable, and it looks like you're handling errors well. I think that's a good way to go.

**Comment by KarelCemus** [comment]
Yes, basically this is just a bit more generic Heroku impl. I made a few changes such as

1) optional auth
2) configurable variable name
3) renamed classes and configuration values as you suggested

But I cannot evaluate if it works for all intended platforms such as Heroku and Azure as I'm not familiar with them.

If you agree so I will merge it to the master and consider the customization for the PaaS sufficient.

**Comment by neilchaudhuri** [comment]
I agree. Maybe you could add a configuration example in the README, but that isn't a big deal.
