### ISSUE TITLE
How to configure for AWS Elasticache 

### ISSUE THREAD

**Issue by nemo83** [KarelCemus/play-redis#219]
Hello,

How can I configure this library when I have one master and a number of (read-)replicas?

I'm asking this because I'm using AWS Elasticache and I have 3 nodes in total of which one master node and two replicas.

Would you recommend switching from Master/Replicas approach to a *proper* Redis Cluster?

Thanks

**Comment by KarelCemus** [comment]
Hi, I am not much familiar with your redis setup, so I cannot much help. However, [#148](https://github.com/KarelCemus/play-redis/issues/148) is a discussion how to use play-redis in AWS, which might help you. And then I suggest you to check [rediscala](https://github.com/etaty/rediscala) library to figure out how to properly configure it for your setup, whether a cluster setup is sufficient or you have something like a sentinel? Then feel free to propose a feature request to address your use case.

Hope this helps.

**Comment by KarelCemus** [comment]
Any feedback on this issue? Or can I close it?

**Comment by nemo83** [comment]
Sorry, was away on holidays. I'm closing this now.

**Comment by KarelCemus** [comment]
Ok, thanks for the update. Could you give me some feedback regarding the status? Whether you succeeded or chose some other solution? Just for a future reference.

**Comment by nemo83** [comment]
We eventually changed approach and used the `Standalone` configuration instead with no read replicas.
