### ISSUE TITLE
Keep accessing the downed node in AWS cluster mode

### ISSUE THREAD

**Issue by yamakz5555** [KarelCemus/play-redis#227]
I have not been able to test, but something like the title is happening.

As long as you read the source code, in the case of AWS cluster mode, resolve the host IP address at startup.
Even if the node goes down and the IP address changes, it doesn't seem to be reflected.

I'm sorry and uncertain. We will add more as soon as we know the details.

**Comment by yamakz5555** [comment]
Amazon ElastiCache for Redis FAQs
https://aws.amazon.com/elasticache/redis/faqs/?nc1=h_ls

> Amazon ElastiCache for Redis will repair the node by acquiring new service resources, and will then redirect the node's existing DNS name to point to the new service resources. Thus, the DNS name for a Redis node remains constant, but the IP address of a Redis node can change over time.


https://github.com/KarelCemus/play-redis/commit/98d5d7bc80f68b8161555e1ef7cb6ecaca89d668#diff-cc72d8a983ca7f131bfb995797dbc98cR113-R119

When is this 'load' method called?
Only at the first startup?

**Comment by KarelCemus** [comment]
Sorry for the late response, I'm busy lately. 

It is unpleasant to hear that IP dynamically changes. Unfortunately, rediscala, which is under the hood, is completely in charge of the reconnection and I am not much able to intercept it to resolve the address again. I worry that the fix must be done directly in [etaty/rediscala](//github.com/etaty/rediscala). Unfortunately, I don't have resources to fix it myself, so feel free to open a ticket or make a PR delivering this fix. You may also consider [this fork](https://github.com/Ma27/rediscala), which seems more active.

**Comment by yamakz5555** [comment]
Thank you for your reply.

I have already released an application that uses cluster mode.

Unfortunately, I'm thinking of fixing it early to avoid using cluster mode. Therefore, there is no need to make any urgent corrections.

I'm sorry that I can't help.
