### ISSUE TITLE
support connection pooling

### ISSUE THREAD

**Issue by pangwa** [KarelCemus/play-redis#228]
It looks like there is no connection pooling config. besides the master-slave pool config. How to config the connection pool for single master setup?

**Comment by KarelCemus** [comment]
Unfortunately, [rediscala](https://github.com/etaty/) library, which is under the hood, does not support pooling for standalone instances and it would be very inconvenient to deal with this at higher levels of abstraction. However, feel free to open a ticket or make a PR in that repo.

**Comment by pangwa** [comment]
I found there is a RedisClientPool which could be used as connection pooling. I'll send a pr.

**Comment by KarelCemus** [comment]
This is intended for multiple servers. 

Anyway, why do you need the pool? This client is non-blocking and asynchronous and the server is single-threaded, so what is the benefit of having another connections?

**Comment by pangwa** [comment]
You're correct, it looks there is no benefits to use pooling connection for single redis instance. I tried enabling pooling but the benchmark doesn't look better...
