### ISSUE TITLE
AWS Redis cluster Connection issue

### ISSUE THREAD

**Issue by cozima0210** [KarelCemus/play-redis#238]
I wonder if there is an issue about https://github.com/KarelCemus/play-redis/pull/221/.
The implementation seems to have some cache of IP address when the application started.
But AWS cluster might change the inside IPs of nodes when the instance went wrong.
For example, could you see below?
https://github.com/debasishg/scala-redis
https://github.com/debasishg/scala-redis/blob/72eeb80ec1f634aea0fa79402bc09e39280e5a77/src/main/scala/com/redis/cluster/RedisCluster.scala
https://github.com/debasishg/scala-redis/blob/72eeb80ec1f634aea0fa79402bc09e39280e5a77/src/main/scala/com/redis/cluster/Reconnectable.scala
It is one of solutions that it has a mechanism to reconnect the nodes when it check if the node can be connectable in interval and it can't be.
I would like to know the strategy in this repository toward this issue.

**Comment by KarelCemus** [comment]
Hi there, this project is just API over a redis connector and therefore the support for reconnection to a different IP address must be implemented directly in the connector. As far as I know rediscala, which is used by this project, does not support AWS cluster directly, the pull request you mentioned is just a minor workaround. However, feel free to contribute this support into rediscala project and I will update dependencies and make it working with this library.

Unfortunatelly, while scala-redis you referenced supports AWS cluster, the implementation of this connector is blocking, while this project prefers non-blocking connectors for a higher throughput.

To directly answer your question - there is no strategy at this moment but you are welcome to contribute.

**Comment by cozima0210** [comment]
Hi @KarelCemus, thanks for quick reply.
I understood your thought. But I am afraid that this issue is not only about the reconnection but also about the scale-in and scale-out.

cf.
https://aws.amazon.com/about-aws/whats-new/2017/11/amazon-elasticache-for-redis-introduces-dynamic-addition-and-removal-of-shards-while-continuing-to-serve-workloads/

I think below line's `node` has the IPs of shards. How about the situation when the number increase or decrease?
https://github.com/KarelCemus/play-redis/pull/221/files#diff-cc72d8a983ca7f131bfb995797dbc98cR116

**Comment by KarelCemus** [comment]
I see and understand your situation. I am afraid that rediscala does not support either of these and play-redis is not a place to implement it. Therefore there must be either a contribution into rediscala project or switch of the underlying connector behind play-redis. I am willing to do that, did it already in the past, but unfortunately, there are no stable and maintained async implementations of redis protocol in java/scala as far as I know :-(

**Comment by KarelCemus** [comment]
Closing for now since there are no actively maintained async redis connectors at this moment, so there is no reasonable alternative connector to contribute to and switch the implementation.

We can revise it in the future if the situation changes.
