### ISSUE TITLE
How to Mocking CacheAsyncApi

### ISSUE THREAD

**Issue by mendiVatbox** [KarelCemus/play-redis#239]
I'm using CacheAsyncApi in my Scala class:

`class AggregationService @Inject()(@NamedCache("name") cache: CacheAsyncApi){}
`
and I want to do a unit test for it.
so tried to do FakeChache with implement the CacheAsyncApi methods.

the problem is that I didn't succeed to implement the 'map' functionality :

the function should be as follow:

`override def map[T](key: String)(implicit evidence$8: ClassTag[T]): RedisMap[T, AsynchronousResult] = ???
`
how to test CacheAsyncApi functionality? And in particular the map functionality

build.sbt includes:
```
`java 8`
scalaVersion := "2.12.8"
  lazy val playLibs = Seq(
    "com.typesafe.play" %% "play-cache" % "2.7.2",
    "com.github.karelcemus" %% "play-redis" % "2.4.0"
  )
```

thanks in advance.

**Comment by KarelCemus** [comment]
I suggest to return mock of `RedisMap[T, AsynchronousResult]`, therefore an instance mocking/implementing all its methods. Have you tried that? Would it work for you? The instance could record calls and return expected values or just use some mocking framework such as scalamock and mock this trait.

**Comment by mendiVatbox** [comment]
Thank you for the super quick answer!
so this is exactly my question, how to implement it? Do you have any example?
how should I return `RedisMap[T, AsynchronousResult]`?

**Comment by KarelCemus** [comment]
This project uses a framework to mock traits, look [here](https://github.com/KarelCemus/play-redis/blob/a2aa83c94edfa7fcb3ece719054f9d38a0d57a54/src/test/scala/play/api/cache/redis/impl/RedisCacheImplicits.scala#L123) how the mock is created and [here](https://github.com/KarelCemus/play-redis/blob/1d3ed211d32c039602bd98f25fd5b60573671236/src/test/scala/play/api/cache/redis/impl/RedisJavaMapSpec.scala) how to use it.

If you want to do it yourself, then there are various ways how to do it, you can google it. You can mock it just as easily as any other trait, there is nothing special about it. Unless you provide more details or your code example, I am unable to help you more. In general, mocks return predefined values and fail on unexpected calls, which both you can easily implement yourself.

However, this issue tracker is not intended for a general discussion on unrelated things, so please either provide specific play-redis related issues or close this ticket.

**Comment by mendiVatbox** [comment]
@KarelCemus this is exactly what I looking for, thank you very much! appreciate it.
