### ISSUE TITLE
Support in-transit encryption?

### ISSUE THREAD

**Issue by JennyLeahy** [KarelCemus/play-redis#240]
We use aws redis with in-transit encryption enabled. Does play-redis support in-transit encryption?

**Comment by KarelCemus** [comment]
It has no explicit support AFAIK. However, check the underlying connector to be sure. https://github.com/etaty/rediscala. I don't know if there must be any kind of support.

**Comment by JennyLeahy** [comment]
Thank @KarelCemus for the quick reply. I've checked https://github.com/etaty/rediscala, but can't see any such support.  Thank you nevertheless.
