### ISSUE TITLE
Update integration docs to use 2.6.1?

### ISSUE THREAD

**Issue by arigoldx** [KarelCemus/play-redis#241]
I'm not positive but I followed [the integration instructions](https://github.com/KarelCemus/play-redis/blob/master/doc/10-integration.md#add-library-into-the-project) and when I tried `2.1.1` I wasn't able to download `play-redis`:

> [error] (update) sbt.librarymanagement.ResolveException: Error downloading com.github.karelcemus:play-redis_2.13:2.1.1

but when I changed `2.1.1` to `2.6.1` then `sbt run` was successful.

That said, I see that an update to integration.md wasn't included in [the commit](https://github.com/KarelCemus/play-redis/commit/21109774f7f26dd15989996f76a900ca58e23f39) which moved to `2.6.1` so maybe there's a reason it's that way?

I'm fairly new to all this so I could most definitely be missing something 😅

**Comment by KarelCemus** [comment]
The reason why SBT fails is that version 2.1.1 is not cross-compiled for Scala 2.13. See the changelog of 2.5.0, it is the first version compiled also for Scala 2.13, which is the version you use.

https://github.com/KarelCemus/play-redis/blob/master/CHANGELOG.md#link-250

**Comment by arigoldx** [comment]
Ah, thanks for the explanation. I'm guessing that you knew we're on 2.13 from the "2.13" before the "2.1.1" in the error message I showed, something new I just learned :)

Out of curiosity, isn't 2.6.1 the latest release of play-redis? Why would the integration document say to use an older version?

> dropped Scala 2.11 since it was discontinued from the Play framework

**Comment by KarelCemus** [comment]
> Out of curiosity, isn't 2.6.1 the latest release of play-redis? Why would the integration document say to use an older version?

Yes, play-redis 2.6.1 is latest release for latest version of play framework.

you need to maintain scala, play framework and play-redis mutual compatibility. Play framework depends on scala and different version's of play are compiled only for some scala versions. Each version of play-redis is tightly coupled to a single minor version of play framework, which transitively includes scala version. 

Therefore if you use older minor version of play, you need to use older version of play-redis. See the readme, there is a compatibility matrix.

**Comment by arigoldx** [comment]
> Therefore if you use older minor version of play, you need to use older version of play-redis.

Agreed, :100: -- I'm just saying that the _documentation_ should have the _current_ version with a caveat like "you might need an older version of play-redis". That makes sense, no?

**Comment by KarelCemus** [comment]
Everyone in play framework community is aware of required compatibility with play version and the documentation includes the compatibility matrix, which highlights the version you want to you https://github.com/KarelCemus/play-redis#compatibility-matrix

**Comment by arigoldx** [comment]
What am I missing?

The documentation, right there in the doc directory, says `2.1.1` under "Add Library into the Project"

play-redis/doc/10-integration.md

no-where in the compatibility matrix does it say `2.1.1`. 

All I'm saying is that maybe that `2.1.1` under "Add Library into the Project" should say something _other_ than `2.1.1` -- maybe `2.6.1` because I'm pretty sure the standard thing for a library to do is to use the most up-to-date-and-stable version. Since Play 2.8.x is out there and stable, I'd imagine that the documentation should reflect that.

Honestly tho, like I said, I might be missing something. I've been coding for 30+ years but am new to Play and Java and Redis.

**Comment by KarelCemus** [comment]
I see, I'll fix the version in docs
