### ISSUE TITLE
OneForOneStrategy error after connecting to AWS

### ISSUE THREAD

**Issue by arigoldx** [KarelCemus/play-redis#244]
### Description of issue

I've followed the [aws-cluster config instructions](https://github.com/KarelCemus/play-redis/blob/2.6.1/doc/20-configuration.md#aws-cluster):

```
play.cache.redis {
  instances {
    play {
      host = <super-fancy-url>
      source = aws-cluster
    }
    authenticated-user-cache {
      host = <super-fancy-url>
      source = aws-cluster
    }
    role-cache {
      host = <super-fancy-url>
      source = aws-cluster
    }
  }
}
```

The connection, at first, appears ok:

```
[info] p.a.cache.redis - Redis cluster cache actor started. It is connected to  <ip>:6379
[info] r.a.RedisClientActor - Connect to /<ip>:6379
[info] r.a.RedisClientActor - Connected to <aws-dns-name>/<ip>:6379
[info] r.a.RedisClientActor - Connect to <aws-dns-name>/<ip>:6379
```

But then I see one of the errors mentioned in https://github.com/KarelCemus/play-redis/issues/148:

```
[error] a.a.OneForOneStrategy - ByteString(45, 69, 82, 82, 32, 84, 104, 105, 115, 32, 105, 110, 115, 116, 97, 110, 99, 101, 32, 104, 97, 115, 32, 99, 108, 117, 115, 116, 101, 114, 32, 115, 117, 112, 112, 111, 114, 116, 32, 100, 105, 115, 97, 98, 108, 101, 100, 13, 10) (of class akka.util.ByteString$ByteString1C)
scala.MatchError: ByteString(45, 69, 82, 82, 32, 84, 104, 105, 115, 32, 105, 110, 115, 116, 97, 110, 99, 101, 32, 104, 97, 115, 32, 99, 108, 117, 115, 116, 101, 114, 32, 115, 117, 112, 112, 111, 114, 116, 32, 100, 105, 115, 97, 98, 108, 101, 100, 13, 10) (of class akka.util.ByteString$ByteString1C)
	at scala.PartialFunction$$anon$1.apply(PartialFunction.scala:341)
	at scala.PartialFunction$$anon$1.apply(PartialFunction.scala:339)
	at redis.protocol.RedisProtocolReply$$anonfun$5.applyOrElse(RedisProtocolReply.scala:164)
	at redis.protocol.RedisProtocolReply$$anonfun$5.applyOrElse(RedisProtocolReply.scala:164)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:35)
	at redis.api.clusters.ClusterSlots$$anonfun$1.applyOrElse(Clusters.scala:67)
	at redis.api.clusters.ClusterSlots$$anonfun$1.applyOrElse(Clusters.scala:58)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:35)
	at redis.Operation.decodeRedisReplyThenComplete(Operation.scala:9)
	at redis.actors.RedisReplyDecoder.decodeRedisReply(RedisReplyDecoder.scala:64)
[info] r.a.RedisClientActor - Connected to <aws>/<ip>:6379
```

### My setup

play-redis 2.6.1
Play 2.8.1
Scala 2.13.2

Any ideas? Things [mostly worked](https://github.com/KarelCemus/play-redis/issues/243) locally so maybe I misconfigured elsewhere?

**Comment by KarelCemus** [comment]
Redis cluster in AWS is not properly supported by the underlying connector. See https://github.com/KarelCemus/play-redis/issues/238 for details.

**Comment by KarelCemus** [comment]
According to the log, the AWS instance is not a cluster but just a standalone instance. Clusters run on different ports. You face the same issues as described in #148. Either changed your config to a standalone instance or change the redis to run in the cluster mode.

**Comment by arigoldx** [comment]
> Either changed your config to a standalone instance

I have yet to deploy it to a cloud server but, locally, that seems to have worked like a charm, thanks :)

I wonder if `source = standalone` isn't just The Way To Do It:tm: when using [Amazon's ElastiCache for Redis](https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/WhatIs.html). If our full deploy shows that this works, I'll open [another](https://github.com/KarelCemus/play-redis/issues/243#issuecomment-781835424) PR to update the docs.

Thanks again!

PS. Speaking of "thanks again" do you have a preferred way for folks to send you a coffee (or 🍸 or 🍺 or whatever :))? Basically I really appreciate the time and would like to do _something_ :muscle:.

**Comment by KarelCemus** [comment]
> I wonder if source = standalone isn't just The Way To Do It™️ when using Amazon's ElastiCache for Redis. If our full deploy shows that this works, I'll open another PR to update the docs.

Not sure what is supposed to be the change in docs? Some people use it with cluster redis also in AWS so both approaches are possible. I believe that use with AWS is pretty straightforward as long as you use a standalone mode. I believe that your way was a bit rocky since you mixed both standalone and cluster modes together.

> Basically I really appreciate the time

I am glad you made it working and that makes me happy ;-) I appreciate your feedback, so don't worry about it.
