### ISSUE TITLE
support expiration smaller then seconds

### ISSUE THREAD

**Issue by Daxten** [KarelCemus/play-redis#247]
Currently the expiration gets transformed into seconds, and fails if it is sub 1 second. I am not sure but 1.5 seconds will also get truncated to 1 second I think

Shouldn't redis also support expirations like `100.millis` ?

**Comment by KarelCemus** [comment]
Expiration is implemented using `SETEX` command, which accepts only seconds, see [docs](https://redis.io/commands/setex). I don't know if there is any other command, which could be used and accepts milliseconds. If so, could you provide a link?

**Comment by Daxten** [comment]
https://redis.io/commands/pexpire supports milliseconds for example (but the SET has to be manually be used beforehand)
since SETEX is equivalent to `SET` and then `EXPIRE` I think the only difference would be that the lib will have to send 2 commands

**Comment by Daxten** [comment]
Ah just checked, I am not too familiar with REDIS sorry: https://redis.io/commands/setex has already documentated that it is the same as sending the 2 commands in a `MULTI` block

**Comment by KarelCemus** [comment]
I see, then this is probably what you need https://redis.io/commands/psetex. I'll see if it can be easily changed or need to make it as another command

**Comment by KarelCemus** [comment]
Fixed in #261
