### ISSUE TITLE
Brando Repository Down

### ISSUE THREAD

**Issue by neilchaudhuri** [KarelCemus/play-redis#25]
Not a bug--just a quick note that Brando is down.

**Comment by KarelCemus** [comment]
I don't think the repo is down. I upgraded to Brando 3.0.3-SNAPSHOT and the library is not published yet. Thus I enabled build of the dependency directly from the sources. Hopefully this works. 

However, there is a change it does not work in the projects including the play-redis, I haven't tested it.

Nevertheless, this solution is just temporary until they'll release the 3.0.3 version

**Comment by KarelCemus** [comment]
> Thus I enabled build of the dependency directly from the sources. Hopefully this works.

Look into `build.sbt` how it's done.

**Comment by KarelCemus** [comment]
I confirm the issue. The current configuration is unable to transitively build brando from sources. I'll revert back to brando v2 until they'll release v3.0.3

**Comment by KarelCemus** [comment]
Reverted. Soon there should be a new snapshot using v2 again.

**Comment by neilchaudhuri** [comment]
This should resolve now:

libraryDependencies += "com.digital-achiever" %% "brando" % "3.0.3"

**Comment by KarelCemus** [comment]
See #28
