### ISSUE TITLE
Load Redis configuration at runtime

### ISSUE THREAD

**Issue by raokrutarth** [KarelCemus/play-redis#251]
My application does not have the redis connection string available in an env var or in the .conf file. It makes a request at bootstrap to get credentials from a secure service. 

Is it possible to initiate the cache with credentials passed at runtime?

e.g. `cache: CacheAsyncApi = CacheAsyncApi(host=hostFromSomewhere, port=portFromSomewhere)`

**Comment by KarelCemus** [comment]
You are looking for `source: custom` . See docs [here](https://github.com/KarelCemus/play-redis/blob/master/doc/20-configuration.md#running-in-different-environments).

You must use source custom and provide your own implementation of [RedisInstance](https://github.com/KarelCemus/play-redis/blob/762026bade28b67273a38455a2b226c3cc739c45/src/main/scala/play/api/cache/redis/configuration/RedisInstance.scala#L7) which may freely reuse existing implementations such as `Standalone` but with customized host and port.

Hope it helps

**Comment by raokrutarth** [comment]
Is there an example I can look at? I'm trying to understand the code [here](https://github.com/KarelCemus/play-redis/blob/762026bade28b67273a38455a2b226c3cc739c45/src/main/scala/play/api/cache/redis/configuration/RedisInstanceProvider.scala) but not yet sure how to proceed.

**Comment by raokrutarth** [comment]
Is this still accurate? https://github.com/KarelCemus/play-redis-samples/pull/5/files

**Comment by KarelCemus** [comment]
> Is this still accurate? https://github.com/KarelCemus/play-redis-samples/pull/5/files

Yes, it should be and [this](https://github.com/KarelCemus/play-redis-samples/pull/5/files#diff-b9f2d85677ea8ab85443dc9976be5ef0228ef879048553ec626c3e7640c8f204R62) is what I meant

**Comment by raokrutarth** [comment]
Thank you @KarelCemus! Will give these a shot.
