### ISSUE TITLE
Redis connection down still exception not raised when calling get on cache.map

### ISSUE THREAD

**Issue by nkmittal** [KarelCemus/play-redis#252]
I recently setup AWS ElastiCache for Redis and I am using this library in my Play app server to connect to AWS.
I am using Sync API for `cache.map` abstraction. When connection to AWS Redis is down and when my code below is invoked I am getting `None` inside Try block instead of execution falling into Catch block.
```
try {
         cache.map[String]("Map-EN-ZH").get(in) match {
            case Some(out) => Some(out)
            case None => None // <--- I am getting this value when Redis connection is down
         }
    } catch { .... } 
```
My Versions:
1. play-redis 2.6.1
2. Scala 2.12.6
3. Play 2.6.25

Thanks.
- Nikhil

**Comment by nkmittal** [comment]
Any update on this issue ?

**Comment by KarelCemus** [comment]
This is not an issue, it is a feature. This library is not a redis connector, it is a cache API designed in a way that the app should work even when the cache is down though it might be inefficient/slow. Therefore when the redis is down, API returns values in a way like there is no cache at all.

However, there exists recovery policy which might solve what you want  https://github.com/KarelCemus/play-redis/blob/master/doc/20-configuration.md#recovery-policy

**Comment by nkmittal** [comment]
Thanks. Recovery policy helps for my use case.
