### ISSUE TITLE
Can custom configuration support returning host and port at the same time?

### ISSUE THREAD

**Issue by Bugsource** [KarelCemus/play-redis#253]
As the example project shows:
```scala
@Singleton
class CustomRedisInstance @Inject() (config: Configuration) extends RedisStandalone with RedisDelegatingSettings {

  val pathPrefix = "play.cache.redis"

  def name = "play"

  private def defaultSettings =
    RedisSettings.load(
      config.underlying,
      "play.cache.redis")

  def settings: RedisSettings = {
    RedisSettings
      .withFallback(defaultSettings)
      .load(
        config.underlying,
        "play.cache.redis")
  }
  // get connection info from name service, which do the discovering job. 
  def host: String = getConnectionFromNameService().host

  def port: Int = getConnectionFromNameService().port

  def database: Option[Int] = Some(config.get[Int](s"$pathPrefix.database"))

  def password: Option[String] = Some(config.get[String](s"$pathPrefix.password"))
}
```
We cannot get the ip and port of redis instance directly, but through a name service which discovering the redis ip and port by name. `getConnectionFromNameService` will call the rest api of name service, but we expect to do this only once. Like this:
```scala
def getHostAndPort:(String, Int) = {
  val connection = getConnectionFromNameService()
  (connection.host, connection.port)
}
```

**Comment by Bugsource** [comment]
Btw, if business logic can't get the host and port for Redis, how to handle this circumstance? Directly throw an excepetion?

**Comment by Bugsource** [comment]
Another question, if the `play-redis` try to reconnect to `Redis` server, would the method `host` and `port` in `CustomRedisInstance` be called?

**Comment by KarelCemus** [comment]
don't much understand, what is an issue to do something like this:

```
  val foo = getConnectionFromNameService()

  // get connection info from name service, which do the discovering job. 
  def host: String = foo.host

  def port: Int = foo.port
```



> Btw, if business logic can't get the host and port for Redis, how to handle this circumstance? Directly throw an exception?

not sure, this case is probably not covered, exception sounds reasonable

> Another question, if the play-redis try to reconnect to Redis server, would the method host and port in CustomRedisInstance be called?

I don't think so, the provided host and port is passed to rediscala library which handles the reconnection itself

**Comment by Bugsource** [comment]
> don't much understand, what is an issue to do something like this:
> 
> ```
>   val foo = getConnectionFromNameService()
> 
>   // get connection info from name service, which do the discovering job. 
>   def host: String = foo.host
> 
>   def port: Int = foo.port
> ```
> 
> > Btw, if business logic can't get the host and port for Redis, how to handle this circumstance? Directly throw an exception?
> 
> not sure, this case is probably not covered, exception sounds reasonable
> 
> > Another question, if the play-redis try to reconnect to Redis server, would the method host and port in CustomRedisInstance be called?
> 
> I don't think so, the provided host and port is passed to rediscala library which handles the reconnection itself

Hi Karel, `getConnectionFromNameService()` will make a remote call to a name service, and the name service will response with a random-selected `ip` and `port` from the cluster. I  have assumed that each time `play-redis` reconnect would call the API `host` and `port`, so it should make a call to  name service to get the latest `ip` and `port` when reconnect happens. But according to your statement, it seems that the provided host and port would passed to `redisscala` only once. If this is true, there is no much point in getting the  latest `ip` and `port`.

**Comment by Bugsource** [comment]
What is the `redisscala` library? It seems that `play-redis` depends on another redis client lib?

**Comment by Bugsource** [comment]
Is there a way to pass the latest `ip` and `port` to the inner `redis` client when reconnect happens?

**Comment by KarelCemus** [comment]
I don't think so. See https://github.com/etaty/rediscala. Play redis is just a cache implementation over redis with Play's API, it is not redis connector itself and supported use cases are narrowed down to cache-related use
