### ISSUE TITLE
Doesn't support sorted set

### ISSUE THREAD

**Issue by Bugsource** [KarelCemus/play-redis#256]
As pointed by this user(https://github.com/KarelCemus/play-redis/issues/205), the `play-redis` doesn't support sorted set now. However, this data structure has great meaning in business development, such as maintaining a post list ordered by time in a feed system.

**Comment by KarelCemus** [comment]
Alright, thank you for your use case. Are you willing to open a pull request for it?

**Comment by Bugsource** [comment]
sorry, i'd like to participate in this project but i have no much time recently.

**Comment by KarelCemus** [comment]
OK, I'm closing this issue since it is not on the roadmap of the project and you are not able to implement it. If you or anyone in the future will have use case for this and time to open PR, feel free to reopen this ticket

**Comment by Bugsource** [comment]
Hey man, i have implement basic commads of zset and created the PR(https://github.com/KarelCemus/play-redis/pull/258), please review it, thanks.
