### ISSUE TITLE
Redis User/Password

### ISSUE THREAD

**Issue by dzove855** [KarelCemus/play-redis#262]
Hello,

since redis version 6.X.X, you can authenticate with user password, instead of simple password.

Is there any way to do it with this lib or does this need to be implemented?

**Comment by KarelCemus** [comment]
Unfortunately, the underlying `rediscala` project has been dead for a couple of years so before this can be implemented this library must be migrated to a new alternative connector, which is quite a significant work.

**Comment by KarelCemus** [comment]
The feature is already merged in master, will be released with new version of the lib for play 2.9.0 and play 3.0.0 hopefully in the next few days.
