### ISSUE TITLE
4.0.0-M1 not supporting JDK 11?

### ISSUE THREAD

**Issue by Lejdborg** [KarelCemus/play-redis#281]
Are you filing an issue? Please follow these checklists and provide us all the possible information to speed up the process.

### Reporting a bug?
1. Version of play-redis
4.0.0-M1

1. Version of Scala
2.13.12

1. Version of Play
3.0.1

1. Describe the environment if applies (usually in cloud etc.)
OpenJDK 11

1. Describe the expected behavior
The application builds and runs

1. Describe the actual behavior, follow the same scenario
Uncaught exception when running ***: java.lang.UnsupportedClassVersionError: play/cache/redis/AsyncCacheApi has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0

1. Provide instructions to reproduce the issue
It seems play-redis 4.0.0-M1 was built using JDK 17 and therefore do not support all the versions of Java that Play itself does. Earlier builds have worked on JDK 11, so perhaps this was a mistake in the build?

**Comment by KarelCemus** [comment]
Hey, thanks for the report. True, Play still supports JDK 11. However, keep in mind this statement from the official documentation:

> Minimum required Java and sbt version
> 
> Play 2.9 dropped Java 8 support and requires at least Java 11. Other supported Java versions are 17 and 21. When upgrading to Play 2.9, **we strongly recommend considering an upgrade to at least Java 17 LTS**. It’s worth noting that in the forthcoming Play 2.x release, which will be version 2.10, we are likely to discontinue support for Java 11.


I'll release new versions compiled against JDK 11

**Comment by Lejdborg** [comment]
Thank you. We will be upgrading to JDK 21 soon

**Comment by KarelCemus** [comment]
Released `4.0.0-M2` and `3.0.0-M4`

**Comment by Lejdborg** [comment]
4.0.0-M2 solved the issue, thank you for quick action!
