### ISSUE TITLE
When Redis cannot be linked, the program will not be able to access it properly

### ISSUE THREAD

**Issue by zhaodaye2022** [KarelCemus/play-redis#304]
Are you filing an issue? Please follow these checklists and provide us all the possible information to speed up the process.

### Reporting a bug?
1. Version of play-redis 5.0.0
1. Version of Scala 2.13.13
1. Version of Play 3.0.3
1. Describe the environment if applies (usually in cloud etc.)
1. Describe the expected behavior
1. Describe the actual behavior, follow the same scenario
1. Provide instructions to reproduce the issue

### Proposing a feature?

Execution exception
[CreationException: Unable to create injector, see the following errors:

1) [Guice/ErrorInCustomProvider]: RedisConnectionException: Unable to connect to localhost:6379
  at GuiceProvider$QualifiedBindingKey.toBindings(RedisCacheModule.scala:58):
Binding(interface CacheApi qualified with QualifierInstance(@NamedCache(value=play)) to ProviderTarget(NamedCacheInstanceProvider@52961fd7))
      \_ installed by: Modules$OverrideModule -> GuiceableModuleConversions$$anon$4
  while locating CacheApi annotated with @NamedCache(value=play)
  at operations.WindowImpl.<init>(WindowImpl.scala:24)
      \_ for 1st parameter cacheApi
  at operations.WindowImpl.class(WindowImpl.scala:23)
  at CacheInit.<init>(CacheInit.scala:27)
      \_ for 1st parameter windowImpl
  at modules.CacheInitModule.<init>(CacheInitModule.scala:14):
Binding(class CacheInit to self eagerly)
      \_ installed by: Modules$OverrideModule -> GuiceableModuleConversions$$anon$4
  while locating CacheInit

Learn more:
  https://github.com/google/guice/wiki/ERROR_IN_CUSTOM_PROVIDER

1 error

======================
Full classname legend:
======================
CacheApi:                           "play.api.cache.redis.CacheApi"
CacheInit:                          "modules.impl.CacheInit"
GuiceProvider$QualifiedBindingKey:  "play.api.cache.redis.GuiceProvider$QualifiedBindingKey"
GuiceableModuleConversions$$anon$4: "play.api.inject.guice.GuiceableModuleConversions$$anon$4"
Modules$OverrideModule:             "com.google.inject.util.Modules$OverrideModule"
NamedCache:                         "play.cache.NamedCache"
NamedCacheInstanceProvider:         "play.api.cache.redis.NamedCacheInstanceProvider"
RedisConnectionException:           "io.lettuce.core.RedisConnectionException"
========================
End of classname legend:
========================
]

No source available, here is the exception stack trace:
->com.google.inject.CreationException: Unable to create injector, see the following errors:

1) [Guice/ErrorInCustomProvider]: RedisConnectionException: Unable to connect to 10.0.10.101:30079
  at GuiceProvider$QualifiedBindingKey.toBindings(RedisCacheModule.scala:58):
Binding(interface CacheApi qualified with QualifierInstance(@NamedCache(value=play)) to ProviderTarget(NamedCacheInstanceProvider@52961fd7))
      \_ installed by: Modules$OverrideModule -> GuiceableModuleConversions$$anon$4
  while locating CacheApi annotated with @NamedCache(value=play)
  at operations.WindowImpl.<init>(WindowImpl.scala:24)
      \_ for 1st parameter cacheApi
  at operations.WindowImpl.class(WindowImpl.scala:23)
  at CacheInit.<init>(CacheInit.scala:27)
      \_ for 1st parameter windowImpl
  at modules.CacheInitModule.<init>(CacheInitModule.scala:14):
Binding(class CacheInit to self eagerly)
      \_ installed by: Modules$OverrideModule -> GuiceableModuleConversions$$anon$4
  while locating CacheInit

Learn more:
  https://github.com/google/guice/wiki/ERROR_IN_CUSTOM_PROVIDER

1 error

======================
Full classname legend:
======================
CacheApi:                           "play.api.cache.redis.CacheApi"
CacheInit:                          "modules.impl.CacheInit"
GuiceProvider$QualifiedBindingKey:  "play.api.cache.redis.GuiceProvider$QualifiedBindingKey"
GuiceableModuleConversions$$anon$4: "play.api.inject.guice.GuiceableModuleConversions$$anon$4"
Modules$OverrideModule:             "com.google.inject.util.Modules$OverrideModule"
NamedCache:                         "play.cache.NamedCache"
NamedCacheInstanceProvider:         "play.api.cache.redis.NamedCacheInstanceProvider"
RedisConnectionException:           "io.lettuce.core.RedisConnectionException"
========================
End of classname legend:
========================
     com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:589)
     com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:190)
     com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:113)
     com.google.inject.Guice.createInjector(Guice.java:87)
     com.google.inject.Guice.createInjector(Guice.java:78)
     play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:200)
     play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:176)
     play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
     play.core.server.DevServerStart$DevServerApplicationProvider$1.$anonfun$reload$2(DevServerStart.scala:233)
     play.utils.Threads$.withContextClassLoader(Threads.scala:22)
     play.core.server.DevServerStart$DevServerApplicationProvider$1.reload(DevServerStart.scala:225)
     play.core.server.DevServerStart$DevServerApplicationProvider$1.get(DevServerStart.scala:190)
     play.core.server.PekkoHttpServer.handleRequest(PekkoHttpServer.scala:320)
     play.core.server.PekkoHttpServer.$anonfun$createServerBinding$1(PekkoHttpServer.scala:224)
     org.apache.pekko.stream.impl.fusing.MapAsyncUnordered$$anon$31.onPush(Ops.scala:1443)
     org.apache.pekko.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:555)
     org.apache.pekko.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:506)
     org.apache.pekko.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:400)
     org.apache.pekko.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:662)
     org.apache.pekko.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:532)
     org.apache.pekko.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:637)
     org.apache.pekko.stream.impl.fusing.ActorGraphInterpreter.org$apache$pekko$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:813)
     org.apache.pekko.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:831)
     org.apache.pekko.actor.Actor.aroundReceive(Actor.scala:547)
     org.apache.pekko.actor.Actor.aroundReceive$(Actor.scala:545)
     org.apache.pekko.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:729)
     org.apache.pekko.actor.ActorCell.receiveMessage(ActorCell.scala:590)
     org.apache.pekko.actor.ActorCell.invoke(ActorCell.scala:557)
     org.apache.pekko.dispatch.Mailbox.processMailbox(Mailbox.scala:280)
     org.apache.pekko.dispatch.Mailbox.run(Mailbox.scala:241)
     org.apache.pekko.dispatch.Mailbox.exec(Mailbox.scala:253)
     java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
     java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
     java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
     java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
     java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

**Comment by KarelCemus** [comment]
This is the issue for the lettuce connector you created. It connects to redis eagerly and when the connection is not available at the moment of RedisConnector creation, it fails. You either need to have the redis running or refactor the connector in this library in order not to fail when the redis is not available. 

I encountered this while I was fixing tests

**Comment by zhaodaye2022** [comment]
Can we capture this exception and add an automatic reconnection mechanism in RedisConnector

**Comment by KarelCemus** [comment]
reconnection seems to be implemented by lettuce itself, I tried to check, the issue is that it requires having available connection at the beginning. We could provide our own retry mechanism but I'd expect lettuce has something on its own as it has reconnection.

Could you investigate it? I am not using this lib anymore.

**Comment by zhaodaye2022** [comment]
Okay, I'll try this question

**Comment by zhaodaye2022** [comment]
Follow this link https://github.com/redis/lettuce/issues/742 This problem can only be solved by oneself, so it is temporarily closed
