### ISSUE TITLE
Supporting scala version 2.10.x

### ISSUE THREAD

**Issue by midnightradio** [KarelCemus/play-redis#63]
I just spent a couple of hours with figuring out some compilation error, which turned out play-redis doesn't release binary compiled with scala 2.10.x. Is there any specific reason for not supporting 2.10.x though 2.10.x is still actively developed and used in common?

**Comment by KarelCemus** [comment]
Hello!

This library is designed for [Play framework](https://playframework.com/) and actively developed and maintained for the most recent version, i.e., 2.5.x, which also [does not support Scala 2.10](https://playframework.com/documentation/2.5.x/Migration25#Scala-2.10-support-discontinued).

Older version could have been compiled also for 2.10 but no one has raised that request so far, and it was originally intended as my personal library and I was using Scala 2.11.

If you are interested in an older version, tell me which one and I might look at it, or feel free to PR it.

**Comment by midnightradio** [comment]
Thanks for the instant response. I'm using 2.10 because of Apache Spark still not supporting 2.11 and that made me to stuck on Play! 2.4 which I never new they stopped supporting Scala 2.10 since 2.5 before your words. Maybe it's a good point to start getting more familiar with 2.11 . Would like to contribute to this project, but I don't feel a value for that if Play! stopped supporting 2.10.x. As I just started to use this nice project, let me see what I can do with this nice project. :+1:

**Comment by midnightradio** [comment]
It's not an issue to be resolved and closed but more like a question to be answered. And I got very clear answer for my question. Thanks.

**Comment by KarelCemus** [comment]
Alright, so ... should I try to release 1.0.1 with Scala 2.10 for you? I'm not sure how much breaking changes are there.

**Comment by midnightradio** [comment]
No, that won't be necessary. but thx.
