### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by jonjack** [KarelCemus/play-redis#67]
Hi Karel,

Play `2.5.8`
Scala `2.11.8`

I was just upgrading to your latest milestone and got the following error:

```
/development/code/jonjack/fyb-server/build.sbt:31: error: not found: value PlayImport
libraryDependencies += PlayImport.cache exclude("net.sf.ehcache", "ehcache-core")
                       ^
[error] Type error in expression
```

I tried both the following versions of PlayScala  `2.5.0` and `2.5.8` and same error.

It is fixed by specifying package for `PlayImport` which for me was `play.sbt.PlayImport`:

So following is successful.

`libraryDependencies += play.sbt.PlayImport.cache exclude("net.sf.ehcache", "ehcache-core")
`

Anyway, maybe I am missing some config. which meant I had to specify fully qualified name. But just in case others have the same problem as me I thought I would let you know in case you thought it useful to update your README. Maybe my config. is not the norm though.

Keep up the great work.
Jon

**Comment by KarelCemus** [comment]
Hi Jon,

thanks for the report. You are correct. I somehow (poorly) assumed `PlayImport` is autoimported. My bad, I'll fix readme first thing tomorrow.

If you encounter any other issues, please, report them.

Thanks!

**Comment by jonjack** [comment]
Hi Karel,

You’re very welcome. I will report back any other issues if I find any.

Many thanks
