### ISSUE TITLE
Check Redis connection possible?

### ISSUE THREAD

**Issue by chrissom** [KarelCemus/play-redis#76]
Hi,

@KarelCemus Is it possible to check if Redis is up or not? Something like ```cache.redis.isUp```.

**Comment by KarelCemus** [comment]
Hi, not right now. May I ask you what is your scenario? 

The intention behind this module is use of Redis as a cache. My understanding of that is that it should be always up and if not, that it's major error. However, I think it should not break the application if possible (that is why it provides several policies). Nevertheless, I cannot imagine the reason why the application could need to test if the redis is up.

**Comment by chrissom** [comment]
It's about API monitoring. I expose a route ```health``` and get a json document with each api components' state.

```
http localhost:9000/health                                                                                                                                               
HTTP/1.1 200 OK
Content-Length: 41
Content-Type: application/json
Date: Fri, 06 Jan 2017 12:26:29 GMT

{
    "cache": "up",
    "database": "up"
}
```

For Redis, I just write and check a value but I was wondering if play-redis expose a more elegante way to check the Redis state.

**Comment by KarelCemus** [comment]
Well, what about [PING](https://github.com/KarelCemus/play-redis/blob/master/src/main/scala/play/api/cache/redis/connector/RedisConnector.scala#L84)? It would ping Redis and if the Future resolves and not fails then it works. Would it work for you? I believe that it is the best way because you will get "the latest" status.

The only issue I see is the `RedisConnector` is private to `redis` package, but I could make it public if needed.

**Comment by chrissom** [comment]
Looks a good way to expose ```RedisConnector``` :)

**Comment by KarelCemus** [comment]
Alright, I'll do it, probably today and schedule it for the 1.3.1 release. But I won't publish it right away, I'll do it later in case something else occurs.

You can workaround it or use SNAPSHOT if you are fine with it.

**Comment by chrissom** [comment]
Another way could be exposing a method ```cache.isRedisUp``` which just wrap the PING method.

What do you think?

**Comment by KarelCemus** [comment]
I am not sure about having such a method in `CacheApi`. Personally, I don't think it belongs there, it is too low level.

**Comment by chrissom** [comment]
You right. 

I will play with the snapshot 👍

**Comment by KarelCemus** [comment]
Should be resolved. Don't forget to use resolver for Sonatype snapshots repository.

**Comment by chrissom** [comment]
quickly, how can I access to ```RedisConnector```?

**Comment by KarelCemus** [comment]
Inject it via DI

**Comment by chrissom** [comment]
It works like a charm!

```
def isRedisUp: Future[Boolean] = {
    redis.ping.map { _ =>
      true
    }.recover {
      case _: Exception => false
    }
}
```

Too bad that Scredis [log errors](https://github.com/Livestream/scredis/blob/master/src/main/scala/scredis/io/IOActor.scala#L162) instead of managing error with Exception. Each time I use ```isRedisUp```my log file is populated with: 
````
[error] s.io.IOActor - Could not connect to localhost/127.0.0.1:6479: Command failed
````

**Comment by KarelCemus** [comment]
Well, it seems to me like correct behavior. You could suppress those logs, but you probably do not want it. I am not sure I can help you any more.

Or do you have any thoughts?

**Comment by chrissom** [comment]
All his good for me. Thanks for your reactivity.

**Comment by chrissom** [comment]
Just to notify, I got a warning since I use the snapshot.

```
SBT project import
[warn] Unable to reparse com.github.karelcemus#play-redis_2.11;1.3.1-SNAPSHOT from sonatype-snapshots
```

**Comment by KarelCemus** [comment]
This is standard SBT warning that you are using a snapshot. Don't worry about that.

**Comment by KarelCemus** [comment]
Published 1.3.1, it will be in maven repos in couple hours.

**Comment by tlehoux** [comment]
> Inject it via DI

@KarelCemus @ChristoRibeiro 
I fail to access  `RedisConnector` with DI, and I really dont see why. Here is my code :

```
package services

import javax.inject.Inject
import play.api.cache.redis.connector.RedisConnector
import scala.concurrent.Future

class HealthCheck @Inject() (redis: RedisConnector) {
   def isRedisUp: Future[Boolean] = {
      redis.ping.map { _ =>
        true
      }.recover {
        case _: Exception => false
      }
  }
}
```
Here is the exception: 
```
No implementation for play.api.cache.redis.connector.RedisConnector was bound.
  while locating play.api.cache.redis.connector.RedisConnector
```
playframework version : 2.6.x
play-redis version : 2.3.0

**Comment by KarelCemus** [comment]
It looks that `RedisConnector` is no longer exposed. This issue related to version `1.x.x` of play-redis, while version `2.x.x` significantly refactored API and internal mechanisms and thus probably dropped this binding. Subscribe to #212 for future updates.
