### ISSUE TITLE
Support for compile time DI

### ISSUE THREAD

**Issue by asheshambasta** [KarelCemus/play-redis#78]
Any pointers on how to use this without DI would be helpful.

**Comment by KarelCemus** [comment]
What do you mean by "without DI"? Play framework since 2.5.x enfoces some kind of DI, at least compile-time DI.

**Comment by asheshambasta** [comment]
Sorry my bad, but I meant compile time DI, which is how I'm using it for my current project anyway.

**Comment by KarelCemus** [comment]
Oh, I see. Well, as I am not using it, I do not see much into it. I can take a look at it or some help or guide how it should work would be appreciated.

**Comment by asheshambasta** [comment]
Yeah, I'll see if I can come up with something. To use play's cache API with compile time DI, you need to mix in the `EhCacheComponents` into `BuiltInComponentsFromContext`.

**Comment by KarelCemus** [comment]
Ok, I'll look at it. Thanks for the initial help.
