### ISSUE TITLE
Support for Redis MGET and MSET

### ISSUE THREAD

**Issue by pcejrowski** [KarelCemus/play-redis#80]
Hi,
it would be great to have the support for Redis MGET operation.
https://redis.io/commands/mget

If I find time this week, I will make a PR.

**Comment by pcejrowski** [comment]
@KarelCemus could please take a look at the PR?

**Comment by KarelCemus** [comment]
Hi, sure, thanks for your contribution. I will look at it, but probably tomorrow. Today I won't make it.

**Comment by pcejrowski** [comment]
Ok, thanks.

**Comment by KarelCemus** [comment]
I created another PR modifying yours. I fixed several issues, refactored the code, wrote README. For more details see #81 .

@pcejrowski Could you look at it, please?

**Comment by pcejrowski** [comment]
I took a look. Looks pretty cool. Thanks.

**Comment by KarelCemus** [comment]
Thanks for the review. Then I'll merge it right away and it will be available as 1.3.2-SNAPSHOT in couple minutes. I will keep it like that for a few days to let people to test it and then probably about the end of the week or in the beginning of the next week I will release 1.3.2.

Will it work for you?

**Comment by pcejrowski** [comment]
Yes, sounds great!

**Comment by KarelCemus** [comment]
I am about to release new version as I announced but I run into some troubles with an update of specs2 library. It may delay it a bit.

**Comment by pcejrowski** [comment]
Thanks for update.

**Comment by KarelCemus** [comment]
Released as 1.4.0
