### ISSUE TITLE
Play 2.6.x

### ISSUE THREAD

**Issue by KarelCemus** [KarelCemus/play-redis#89]
Update to `Play 2.6.x`, more specifically support its new `cacheApi` module introducing sync and async API.

**Comment by scozv** [comment]
@KarelCemus 

Hi, may I know when will you plan to release 1.5.0 for Play 2.6 and Scala 2.12 ?

Thanks

**Comment by KarelCemus** [comment]
Hi, well, it is prepared as a snapshot and it should work, so feel free to test it. 

However, there are several internal issues I want to resolve before the stable release but as I am a bit short on time right now, I am considering releasing a milestone or postponing the refactoring for a subsequent release. Either way, I need some feedback that it is actually working with Play 2.6 before I publish a stable release. I haven't used it yet myself.

**Comment by KarelCemus** [comment]
@scozv Are you willing to test it actually works with Play 2.6? It would be much help, I'd appreciate. Basically, I am worried only about the configuration, otherwise, it should be alright.

**Comment by scozv** [comment]
Yes, I am willing to test it on Play 2.6 and Scala 2.12. 

Currently, I just put the your master dependency in my `build.sbt` (see below).

Before Play 2.6, I am using the `com.typesafe.play.plugins %% play-plugins-redis` for Play 2.3.

So I need some time to upgrade my source code, and test the `play-redis` on Play 2.6.

I will let you know, if I have any feather questions. Thanks.

```
lazy val playRedis = RootProject(uri("git://github.com/KarelCemus/play-redis"))

lazy val root = (project in file("."))
  .enablePlugins(PlayScala)
  .dependsOn(playRedis)
```

**Comment by KarelCemus** [comment]
Great, thanks! Don't forget to enable Sonatype snapshots resolver, might be necessary. Keep me posted, if anything, feel free to ask.

**Comment by KarelCemus** [comment]
Well, looking at your configuration, you make it too complicated. Just add this and you should be fine

```
libraryDependencies += play.sbt.PlayImport.cacheApi
// include play-redis library
libraryDependencies += "com.github.karelcemus" %% "play-redis" % "1.5.0-SNAPSHOT"

resolvers +=Resolver.sonatypeRepo( "snapshots" )

**Comment by scozv** [comment]
Thank, but in your master, your version is `1.4.2-SNAPSHOT` right now.  :)

https://oss.sonatype.org/content/repositories/public/com/github/karelcemus/play-redis_2.12/

```
1.4.2-SNAPSHOT/	Mon Jun 12 03:58:36 UTC 2017	 	
```

**Comment by KarelCemus** [comment]
My bad, I forgot to update the `version.sbt`. Travis [is already building](https://travis-ci.org/KarelCemus/play-redis/builds/242752502) `1.5.0-SNAPSHOT`. Thanks!

**Comment by KarelCemus** [comment]
@scozv Please let's move to #95, this issue was about migrating the code to Play 2.6.
