### ISSUE TITLE
Do not wait for confirmation

### ISSUE THREAD

**Issue by KarelCemus** [KarelCemus/play-redis#98]
There are various scenarios where it is not necessary to wait for actual invocation of the redis command. Among these cases belong `set` and `remove` operations especially within `getOrElse` and `getOrFuture` operations.

This issue proposes a new methods or policy enabling us to execute these methods with the expectation of a positive result and without waiting for a confirmation.

This issue raised from #94.

**Comment by KarelCemus** [comment]
@guizmaii Resolved in version `2.0.0` (not release yet). Check [the wiki](https://github.com/KarelCemus/play-redis/wiki/How-to-Use#eager-and-lazy-invocation) for more details.

**Comment by guizmaii** [comment]
Ok Thanks  ! :)
